/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_VERBQUERYLANGUAGE_WRAP_H_
#define SWIG_VERBQUERYLANGUAGE_WRAP_H_

class SwigDirector_VerbQueryLanguage : public VerbQueryLanguage, public Swig::Director {

public:
    SwigDirector_VerbQueryLanguage(zval *self);
    virtual ~SwigDirector_VerbQueryLanguage();
    virtual char *resolvePath(char *path);
};

#endif
