/** \file
 *  This C source file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : VerbQueryLanguage.g
 *     -                            On : 2010-06-06 15:39:11
 *     -                for the parser : VerbQueryLanguageParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "VerbQueryLanguageParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pVerbQueryLanguageParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pVerbQueryLanguageParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pVerbQueryLanguageParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pVerbQueryLanguageParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   VerbQueryLanguageParserTokenNames[45+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "NODE_STRING",
        (pANTLR3_UINT8) "NODE_VARIABLE",
        (pANTLR3_UINT8) "NODE_OPERATOR",
        (pANTLR3_UINT8) "NODE_FUNCTION",
        (pANTLR3_UINT8) "NODE_PREDICATE",
        (pANTLR3_UINT8) "NODE_PATH",
        (pANTLR3_UINT8) "SLASH",
        (pANTLR3_UINT8) "SQL",
        (pANTLR3_UINT8) "AT",
        (pANTLR3_UINT8) "EQUALITY",
        (pANTLR3_UINT8) "EQUALITY_ALT",
        (pANTLR3_UINT8) "INEQUALITY",
        (pANTLR3_UINT8) "INEQUALITY_ALT",
        (pANTLR3_UINT8) "LESS",
        (pANTLR3_UINT8) "LTE",
        (pANTLR3_UINT8) "GREATER",
        (pANTLR3_UINT8) "GTE",
        (pANTLR3_UINT8) "AND",
        (pANTLR3_UINT8) "OR",
        (pANTLR3_UINT8) "XOR",
        (pANTLR3_UINT8) "NOT",
        (pANTLR3_UINT8) "ADD",
        (pANTLR3_UINT8) "SUB",
        (pANTLR3_UINT8) "MULT",
        (pANTLR3_UINT8) "MOD",
        (pANTLR3_UINT8) "IFTRUE",
        (pANTLR3_UINT8) "IFFALSE",
        (pANTLR3_UINT8) "LBRACKET",
        (pANTLR3_UINT8) "RBRACKET",
        (pANTLR3_UINT8) "LPAREN",
        (pANTLR3_UINT8) "RPAREN",
        (pANTLR3_UINT8) "COMMA",
        (pANTLR3_UINT8) "PATH",
        (pANTLR3_UINT8) "VARIABLE",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "FLOAT",
        (pANTLR3_UINT8) "FUNCTION",
        (pANTLR3_UINT8) "AXIS",
        (pANTLR3_UINT8) "AND_ALT",
        (pANTLR3_UINT8) "OR_ALT",
        (pANTLR3_UINT8) "XOR_ALT",
        (pANTLR3_UINT8) "ESC_SEQ",
        (pANTLR3_UINT8) "PATH_END",
        (pANTLR3_UINT8) "WS"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static VerbQueryLanguageParser_start_return	start    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_sqlquery_return	sqlquery    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_expr_return	expr    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_value_expr_return	value_expr    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_value_return	value    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_function_return	function    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_path_return	path    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_predicate_return	predicate    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_operator_return	operator    (pVerbQueryLanguageParser ctx);
static void	VerbQueryLanguageParserFree(pVerbQueryLanguageParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "VerbQueryLanguage.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new VerbQueryLanguageParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pVerbQueryLanguageParser
VerbQueryLanguageParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return VerbQueryLanguageParserNewSSD(instream, NULL);
}

/** \brief Create a new VerbQueryLanguageParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pVerbQueryLanguageParser
VerbQueryLanguageParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pVerbQueryLanguageParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pVerbQueryLanguageParser) ANTLR3_CALLOC(1, sizeof(VerbQueryLanguageParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in VerbQueryLanguageParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our VerbQueryLanguageParser interface
     */
    ctx->start	= start;
    ctx->sqlquery	= sqlquery;
    ctx->expr	= expr;
    ctx->value_expr	= value_expr;
    ctx->value	= value;
    ctx->function	= function;
    ctx->path	= path;
    ctx->predicate	= predicate;
    ctx->operator	= operator;
    ctx->free			= VerbQueryLanguageParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */
    ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);
    ctx->vectors	= antlr3VectorFactoryNew(0);
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = VerbQueryLanguageParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 VerbQueryLanguageParserFree(pVerbQueryLanguageParser ctx)
 {
    /* Free any scope memory
     */
    
    ctx->vectors->close(ctx->vectors);
    /* We created the adaptor so we must free it
     */
    ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return VerbQueryLanguageParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_start306  */
static	ANTLR3_BITWORD FOLLOW_expr_in_start306_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_start306	= { FOLLOW_expr_in_start306_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sqlquery_in_start310  */
static	ANTLR3_BITWORD FOLLOW_sqlquery_in_start310_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_sqlquery_in_start310	= { FOLLOW_sqlquery_in_start310_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_start313  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_start313_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_start313	= { FOLLOW_EOF_in_start313_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SQL_in_sqlquery325  */
static	ANTLR3_BITWORD FOLLOW_SQL_in_sqlquery325_bits[]	= { ANTLR3_UINT64_LIT(0x0000001000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_SQL_in_sqlquery325	= { FOLLOW_SQL_in_sqlquery325_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PATH_in_sqlquery327  */
static	ANTLR3_BITWORD FOLLOW_PATH_in_sqlquery327_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_PATH_in_sqlquery327	= { FOLLOW_PATH_in_sqlquery327_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NOT_in_expr346  */
static	ANTLR3_BITWORD FOLLOW_NOT_in_expr346_bits[]	= { ANTLR3_UINT64_LIT(0x000007F201001000) };
static  ANTLR3_BITSET_LIST FOLLOW_NOT_in_expr346	= { FOLLOW_NOT_in_expr346_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_expr348  */
static	ANTLR3_BITWORD FOLLOW_expr_in_expr348_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_expr348	= { FOLLOW_expr_in_expr348_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_expr_in_expr362  */
static	ANTLR3_BITWORD FOLLOW_value_expr_in_expr362_bits[]	= { ANTLR3_UINT64_LIT(0x000038001EFFE402) };
static  ANTLR3_BITSET_LIST FOLLOW_value_expr_in_expr362	= { FOLLOW_value_expr_in_expr362_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_operator_in_expr365  */
static	ANTLR3_BITWORD FOLLOW_operator_in_expr365_bits[]	= { ANTLR3_UINT64_LIT(0x000007F201001000) };
static  ANTLR3_BITSET_LIST FOLLOW_operator_in_expr365	= { FOLLOW_operator_in_expr365_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_expr_in_expr368  */
static	ANTLR3_BITWORD FOLLOW_value_expr_in_expr368_bits[]	= { ANTLR3_UINT64_LIT(0x000038001EFFE402) };
static  ANTLR3_BITSET_LIST FOLLOW_value_expr_in_expr368	= { FOLLOW_value_expr_in_expr368_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAREN_in_value_expr382  */
static	ANTLR3_BITWORD FOLLOW_LPAREN_in_value_expr382_bits[]	= { ANTLR3_UINT64_LIT(0x000007F201001000) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAREN_in_value_expr382	= { FOLLOW_LPAREN_in_value_expr382_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_value_expr384  */
static	ANTLR3_BITWORD FOLLOW_expr_in_value_expr384_bits[]	= { ANTLR3_UINT64_LIT(0x0000000400000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_value_expr384	= { FOLLOW_expr_in_value_expr384_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAREN_in_value_expr386  */
static	ANTLR3_BITWORD FOLLOW_RPAREN_in_value_expr386_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAREN_in_value_expr386	= { FOLLOW_RPAREN_in_value_expr386_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_value_expr399  */
static	ANTLR3_BITWORD FOLLOW_value_in_value_expr399_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_value_expr399	= { FOLLOW_value_in_value_expr399_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_function_in_value_expr403  */
static	ANTLR3_BITWORD FOLLOW_function_in_value_expr403_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_function_in_value_expr403	= { FOLLOW_function_in_value_expr403_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_in_value_expr407  */
static	ANTLR3_BITWORD FOLLOW_path_in_value_expr407_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_in_value_expr407	= { FOLLOW_path_in_value_expr407_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_VARIABLE_in_value419  */
static	ANTLR3_BITWORD FOLLOW_VARIABLE_in_value419_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_VARIABLE_in_value419	= { FOLLOW_VARIABLE_in_value419_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_value432  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_value432_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_value432	= { FOLLOW_STRING_in_value432_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_value445  */
static	ANTLR3_BITWORD FOLLOW_INT_in_value445_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_value445	= { FOLLOW_INT_in_value445_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_value449  */
static	ANTLR3_BITWORD FOLLOW_FLOAT_in_value449_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_value449	= { FOLLOW_FLOAT_in_value449_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FUNCTION_in_function460  */
static	ANTLR3_BITWORD FOLLOW_FUNCTION_in_function460_bits[]	= { ANTLR3_UINT64_LIT(0x000007FE01001000) };
static  ANTLR3_BITSET_LIST FOLLOW_FUNCTION_in_function460	= { FOLLOW_FUNCTION_in_function460_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_function462  */
static	ANTLR3_BITWORD FOLLOW_expr_in_function462_bits[]	= { ANTLR3_UINT64_LIT(0x0000000C00000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_function462	= { FOLLOW_expr_in_function462_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COMMA_in_function466  */
static	ANTLR3_BITWORD FOLLOW_COMMA_in_function466_bits[]	= { ANTLR3_UINT64_LIT(0x000007F201001000) };
static  ANTLR3_BITSET_LIST FOLLOW_COMMA_in_function466	= { FOLLOW_COMMA_in_function466_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_function468  */
static	ANTLR3_BITWORD FOLLOW_expr_in_function468_bits[]	= { ANTLR3_UINT64_LIT(0x0000000C00000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_function468	= { FOLLOW_expr_in_function468_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAREN_in_function472  */
static	ANTLR3_BITWORD FOLLOW_RPAREN_in_function472_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAREN_in_function472	= { FOLLOW_RPAREN_in_function472_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PATH_in_path504  */
static	ANTLR3_BITWORD FOLLOW_PATH_in_path504_bits[]	= { ANTLR3_UINT64_LIT(0x0000000080000002) };
static  ANTLR3_BITSET_LIST FOLLOW_PATH_in_path504	= { FOLLOW_PATH_in_path504_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AXIS_in_path510  */
static	ANTLR3_BITWORD FOLLOW_AXIS_in_path510_bits[]	= { ANTLR3_UINT64_LIT(0x0000000080000002) };
static  ANTLR3_BITSET_LIST FOLLOW_AXIS_in_path510	= { FOLLOW_AXIS_in_path510_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_in_path513  */
static	ANTLR3_BITWORD FOLLOW_predicate_in_path513_bits[]	= { ANTLR3_UINT64_LIT(0x0000000080000002) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_in_path513	= { FOLLOW_predicate_in_path513_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AT_in_path531  */
static	ANTLR3_BITWORD FOLLOW_AT_in_path531_bits[]	= { ANTLR3_UINT64_LIT(0x000007F201001000) };
static  ANTLR3_BITSET_LIST FOLLOW_AT_in_path531	= { FOLLOW_AT_in_path531_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_in_path533  */
static	ANTLR3_BITWORD FOLLOW_path_in_path533_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_in_path533	= { FOLLOW_path_in_path533_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LBRACKET_in_predicate552  */
static	ANTLR3_BITWORD FOLLOW_LBRACKET_in_predicate552_bits[]	= { ANTLR3_UINT64_LIT(0x000007F201001000) };
static  ANTLR3_BITSET_LIST FOLLOW_LBRACKET_in_predicate552	= { FOLLOW_LBRACKET_in_predicate552_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_predicate554  */
static	ANTLR3_BITWORD FOLLOW_expr_in_predicate554_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_predicate554	= { FOLLOW_expr_in_predicate554_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RBRACKET_in_predicate556  */
static	ANTLR3_BITWORD FOLLOW_RBRACKET_in_predicate556_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RBRACKET_in_predicate556	= { FOLLOW_RBRACKET_in_predicate556_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_operator0  */
static	ANTLR3_BITWORD FOLLOW_set_in_operator0_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_operator0	= { FOLLOW_set_in_operator0_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start start
 * VerbQueryLanguage.g:51:1: start : ( expr | sqlquery ) EOF ;
 */
static VerbQueryLanguageParser_start_return
start(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_start_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    EOF3;
    VerbQueryLanguageParser_expr_return expr1;
    #undef	RETURN_TYPE_expr1
    #define	RETURN_TYPE_expr1 VerbQueryLanguageParser_expr_return

    VerbQueryLanguageParser_sqlquery_return sqlquery2;
    #undef	RETURN_TYPE_sqlquery2
    #define	RETURN_TYPE_sqlquery2 VerbQueryLanguageParser_sqlquery_return

    pANTLR3_BASE_TREE EOF3_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    EOF3       = NULL;
    expr1.tree = NULL;

    sqlquery2.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    EOF3_tree   = NULL;


    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:52:2: ( ( expr | sqlquery ) EOF )
        // VerbQueryLanguage.g:52:4: ( expr | sqlquery ) EOF
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // VerbQueryLanguage.g:52:4: ( expr | sqlquery )
            {
                int alt1=2;
                switch ( LA(1) ) 
                {
                case AT:
                case NOT:
                case LPAREN:
                case PATH:
                case VARIABLE:
                case STRING:
                case INT:
                case FLOAT:
                case FUNCTION:
                case AXIS:
                	{
                		alt1=1;
                	}
                    break;
                case SQL:
                	{
                		alt1=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 1;
                    EXCEPTION->state        = 0;


                    goto rulestartEx;
                }

                switch (alt1) 
                {
            	case 1:
            	    // VerbQueryLanguage.g:52:5: expr
            	    {
            	        FOLLOWPUSH(FOLLOW_expr_in_start306);
            	        expr1=expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulestartEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, expr1.tree);

            	    }
            	    break;
            	case 2:
            	    // VerbQueryLanguage.g:52:12: sqlquery
            	    {
            	        FOLLOWPUSH(FOLLOW_sqlquery_in_start310);
            	        sqlquery2=sqlquery(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulestartEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, sqlquery2.tree);

            	    }
            	    break;

                }
            }
            EOF3 = (pANTLR3_COMMON_TOKEN) MATCHT(EOF, &FOLLOW_EOF_in_start313); 
            if  (HASEXCEPTION())
            {
                goto rulestartEx;
            }

            EOF3_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, EOF3));
            ADAPTOR->addChild(ADAPTOR, root_0, EOF3_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulestartEx; /* Prevent compiler warnings */
    rulestartEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end start */

/** 
 * $ANTLR start sqlquery
 * VerbQueryLanguage.g:55:1: sqlquery : SQL PATH -> ^( SQL PATH ) ;
 */
static VerbQueryLanguageParser_sqlquery_return
sqlquery(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_sqlquery_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SQL4;
    pANTLR3_COMMON_TOKEN    PATH5;

    pANTLR3_BASE_TREE SQL4_tree;
    pANTLR3_BASE_TREE PATH5_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_SQL;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_PATH;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SQL4       = NULL;
    PATH5       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    SQL4_tree   = NULL;
    PATH5_tree   = NULL;

    stream_SQL   = NULL;
    #define CREATE_stream_SQL  if (stream_SQL == NULL) {stream_SQL = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token SQL"); } 
    stream_PATH   = NULL;
    #define CREATE_stream_PATH  if (stream_PATH == NULL) {stream_PATH = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token PATH"); } 

    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:56:2: ( SQL PATH -> ^( SQL PATH ) )
        // VerbQueryLanguage.g:56:4: SQL PATH
        {
            SQL4 = (pANTLR3_COMMON_TOKEN) MATCHT(SQL, &FOLLOW_SQL_in_sqlquery325); 
            if  (HASEXCEPTION())
            {
                goto rulesqlqueryEx;
            }
             
            CREATE_stream_SQL; stream_SQL->add(stream_SQL, SQL4, NULL);

            PATH5 = (pANTLR3_COMMON_TOKEN) MATCHT(PATH, &FOLLOW_PATH_in_sqlquery327); 
            if  (HASEXCEPTION())
            {
                goto rulesqlqueryEx;
            }
             
            CREATE_stream_PATH; stream_PATH->add(stream_PATH, PATH5, NULL);


             
            /* AST REWRITE
             * elements          : PATH, SQL
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 56:13: -> ^( SQL PATH )
            	{
            	    // VerbQueryLanguage.g:56:16: ^( SQL PATH )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_SQL == NULL ? NULL : stream_SQL->nextNode(stream_SQL), root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_PATH == NULL ? NULL : stream_PATH->nextNode(stream_PATH));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}

            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesqlqueryEx; /* Prevent compiler warnings */
    rulesqlqueryEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_SQL != NULL) stream_SQL->free(stream_SQL);
        if (stream_PATH != NULL) stream_PATH->free(stream_PATH);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end sqlquery */

/** 
 * $ANTLR start expr
 * VerbQueryLanguage.g:59:1: expr : ( NOT expr -> ^( NOT expr ) | value_expr ( operator value_expr )* );
 */
static VerbQueryLanguageParser_expr_return
expr(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_expr_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    NOT6;
    VerbQueryLanguageParser_expr_return expr7;
    #undef	RETURN_TYPE_expr7
    #define	RETURN_TYPE_expr7 VerbQueryLanguageParser_expr_return

    VerbQueryLanguageParser_value_expr_return value_expr8;
    #undef	RETURN_TYPE_value_expr8
    #define	RETURN_TYPE_value_expr8 VerbQueryLanguageParser_value_expr_return

    VerbQueryLanguageParser_operator_return operator9;
    #undef	RETURN_TYPE_operator9
    #define	RETURN_TYPE_operator9 VerbQueryLanguageParser_operator_return

    VerbQueryLanguageParser_value_expr_return value_expr10;
    #undef	RETURN_TYPE_value_expr10
    #define	RETURN_TYPE_value_expr10 VerbQueryLanguageParser_value_expr_return

    pANTLR3_BASE_TREE NOT6_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NOT;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */


    root_0 = NULL;

    NOT6       = NULL;
    expr7.tree = NULL;

    value_expr8.tree = NULL;

    operator9.tree = NULL;

    value_expr10.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    NOT6_tree   = NULL;

    stream_NOT   = NULL;
    #define CREATE_stream_NOT  if (stream_NOT == NULL) {stream_NOT = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NOT"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;
    {
        {
            //  VerbQueryLanguage.g:60:2: ( NOT expr -> ^( NOT expr ) | value_expr ( operator value_expr )* )
            
            ANTLR3_UINT32 alt3;

            alt3=2;

            switch ( LA(1) ) 
            {
            case NOT:
            	{
            		alt3=1;
            	}
                break;
            case AT:
            case LPAREN:
            case PATH:
            case VARIABLE:
            case STRING:
            case INT:
            case FLOAT:
            case FUNCTION:
            case AXIS:
            	{
            		alt3=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto ruleexprEx;
            }

            switch (alt3) 
            {
        	case 1:
        	    // VerbQueryLanguage.g:60:4: NOT expr
        	    {
        	        NOT6 = (pANTLR3_COMMON_TOKEN) MATCHT(NOT, &FOLLOW_NOT_in_expr346); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }
        	         
        	        CREATE_stream_NOT; stream_NOT->add(stream_NOT, NOT6, NULL);

        	        FOLLOWPUSH(FOLLOW_expr_in_expr348);
        	        expr7=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr7.tree, NULL);

        	         
        	        /* AST REWRITE
        	         * elements          : expr, NOT
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 60:13: -> ^( NOT expr )
        	        	{
        	        	    // VerbQueryLanguage.g:60:16: ^( NOT expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_NOT == NULL ? NULL : stream_NOT->nextNode(stream_NOT), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguage.g:61:4: value_expr ( operator value_expr )*
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_value_expr_in_expr362);
        	        value_expr8=value_expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, value_expr8.tree);

        	        // VerbQueryLanguage.g:61:15: ( operator value_expr )*

        	        for (;;)
        	        {
        	            int alt2=2;
        	            switch ( LA(1) ) 
        	            {
        	            case SLASH:
        	            case EQUALITY:
        	            case EQUALITY_ALT:
        	            case INEQUALITY:
        	            case INEQUALITY_ALT:
        	            case LESS:
        	            case LTE:
        	            case GREATER:
        	            case GTE:
        	            case AND:
        	            case OR:
        	            case XOR:
        	            case ADD:
        	            case SUB:
        	            case MULT:
        	            case MOD:
        	            case AND_ALT:
        	            case OR_ALT:
        	            case XOR_ALT:
        	            	{
        	            		alt2=1;
        	            	}
        	                break;

        	            }

        	            switch (alt2) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguage.g:61:16: operator value_expr
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_operator_in_expr365);
        	        	        operator9=operator(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleexprEx;
        	        	        }

        	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, operator9.tree, root_0));
        	        	        FOLLOWPUSH(FOLLOW_value_expr_in_expr368);
        	        	        value_expr10=value_expr(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleexprEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, value_expr10.tree);

        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop2;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop2: ; /* Jump out to here if this rule does not match */


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_NOT != NULL) stream_NOT->free(stream_NOT);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end expr */

/** 
 * $ANTLR start value_expr
 * VerbQueryLanguage.g:64:1: value_expr : ( ( LPAREN expr RPAREN ) -> ^( expr ) | ( value | function | path ) );
 */
static VerbQueryLanguageParser_value_expr_return
value_expr(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_value_expr_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    LPAREN11;
    pANTLR3_COMMON_TOKEN    RPAREN13;
    VerbQueryLanguageParser_expr_return expr12;
    #undef	RETURN_TYPE_expr12
    #define	RETURN_TYPE_expr12 VerbQueryLanguageParser_expr_return

    VerbQueryLanguageParser_value_return value14;
    #undef	RETURN_TYPE_value14
    #define	RETURN_TYPE_value14 VerbQueryLanguageParser_value_return

    VerbQueryLanguageParser_function_return function15;
    #undef	RETURN_TYPE_function15
    #define	RETURN_TYPE_function15 VerbQueryLanguageParser_function_return

    VerbQueryLanguageParser_path_return path16;
    #undef	RETURN_TYPE_path16
    #define	RETURN_TYPE_path16 VerbQueryLanguageParser_path_return

    pANTLR3_BASE_TREE LPAREN11_tree;
    pANTLR3_BASE_TREE RPAREN13_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_RPAREN;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_LPAREN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */


    root_0 = NULL;

    LPAREN11       = NULL;
    RPAREN13       = NULL;
    expr12.tree = NULL;

    value14.tree = NULL;

    function15.tree = NULL;

    path16.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    LPAREN11_tree   = NULL;
    RPAREN13_tree   = NULL;

    stream_RPAREN   = NULL;
    #define CREATE_stream_RPAREN  if (stream_RPAREN == NULL) {stream_RPAREN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token RPAREN"); } 
    stream_LPAREN   = NULL;
    #define CREATE_stream_LPAREN  if (stream_LPAREN == NULL) {stream_LPAREN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token LPAREN"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;
    {
        {
            //  VerbQueryLanguage.g:65:2: ( ( LPAREN expr RPAREN ) -> ^( expr ) | ( value | function | path ) )
            
            ANTLR3_UINT32 alt5;

            alt5=2;

            switch ( LA(1) ) 
            {
            case LPAREN:
            	{
            		alt5=1;
            	}
                break;
            case AT:
            case PATH:
            case VARIABLE:
            case STRING:
            case INT:
            case FLOAT:
            case FUNCTION:
            case AXIS:
            	{
            		alt5=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 5;
                EXCEPTION->state        = 0;


                goto rulevalue_exprEx;
            }

            switch (alt5) 
            {
        	case 1:
        	    // VerbQueryLanguage.g:65:4: ( LPAREN expr RPAREN )
        	    {
        	        // VerbQueryLanguage.g:65:4: ( LPAREN expr RPAREN )
        	        // VerbQueryLanguage.g:65:5: LPAREN expr RPAREN
        	        {
        	            LPAREN11 = (pANTLR3_COMMON_TOKEN) MATCHT(LPAREN, &FOLLOW_LPAREN_in_value_expr382); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto rulevalue_exprEx;
        	            }
        	             
        	            CREATE_stream_LPAREN; stream_LPAREN->add(stream_LPAREN, LPAREN11, NULL);

        	            FOLLOWPUSH(FOLLOW_expr_in_value_expr384);
        	            expr12=expr(ctx);

        	            FOLLOWPOP();
        	            if  (HASEXCEPTION())
        	            {
        	                goto rulevalue_exprEx;
        	            }

        	            CREATE_stream_expr; stream_expr->add(stream_expr, expr12.tree, NULL);
        	            RPAREN13 = (pANTLR3_COMMON_TOKEN) MATCHT(RPAREN, &FOLLOW_RPAREN_in_value_expr386); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto rulevalue_exprEx;
        	            }
        	             
        	            CREATE_stream_RPAREN; stream_RPAREN->add(stream_RPAREN, RPAREN13, NULL);


        	        }


        	         
        	        /* AST REWRITE
        	         * elements          : expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 65:25: -> ^( expr )
        	        	{
        	        	    // VerbQueryLanguage.g:65:28: ^( expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_expr == NULL ? NULL : stream_expr->nextNode(stream_expr), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguage.g:66:4: ( value | function | path )
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        // VerbQueryLanguage.g:66:4: ( value | function | path )
        	        {
        	            int alt4=3;
        	            switch ( LA(1) ) 
        	            {
        	            case VARIABLE:
        	            case STRING:
        	            case INT:
        	            case FLOAT:
        	            	{
        	            		alt4=1;
        	            	}
        	                break;
        	            case FUNCTION:
        	            	{
        	            		alt4=2;
        	            	}
        	                break;
        	            case AT:
        	            case PATH:
        	            case AXIS:
        	            	{
        	            		alt4=3;
        	            	}
        	                break;

        	            default:
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	                EXCEPTION->message      = (void *)"";
        	                EXCEPTION->decisionNum  = 4;
        	                EXCEPTION->state        = 0;


        	                goto rulevalue_exprEx;
        	            }

        	            switch (alt4) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguage.g:66:5: value
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_value_in_value_expr399);
        	        	        value14=value(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulevalue_exprEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, value14.tree);

        	        	    }
        	        	    break;
        	        	case 2:
        	        	    // VerbQueryLanguage.g:66:13: function
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_function_in_value_expr403);
        	        	        function15=function(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulevalue_exprEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, function15.tree);

        	        	    }
        	        	    break;
        	        	case 3:
        	        	    // VerbQueryLanguage.g:66:24: path
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_path_in_value_expr407);
        	        	        path16=path(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulevalue_exprEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, path16.tree);

        	        	    }
        	        	    break;

        	            }
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulevalue_exprEx; /* Prevent compiler warnings */
    rulevalue_exprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_RPAREN != NULL) stream_RPAREN->free(stream_RPAREN);
        if (stream_LPAREN != NULL) stream_LPAREN->free(stream_LPAREN);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end value_expr */

/** 
 * $ANTLR start value
 * VerbQueryLanguage.g:69:1: value : ( VARIABLE -> ^( NODE_VARIABLE VARIABLE ) | STRING -> ^( NODE_STRING STRING ) | INT | FLOAT );
 */
static VerbQueryLanguageParser_value_return
value(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_value_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    VARIABLE17;
    pANTLR3_COMMON_TOKEN    STRING18;
    pANTLR3_COMMON_TOKEN    INT19;
    pANTLR3_COMMON_TOKEN    FLOAT20;

    pANTLR3_BASE_TREE VARIABLE17_tree;
    pANTLR3_BASE_TREE STRING18_tree;
    pANTLR3_BASE_TREE INT19_tree;
    pANTLR3_BASE_TREE FLOAT20_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_VARIABLE;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_STRING;

    /* Initialize rule variables
     */


    root_0 = NULL;

    VARIABLE17       = NULL;
    STRING18       = NULL;
    INT19       = NULL;
    FLOAT20       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    VARIABLE17_tree   = NULL;
    STRING18_tree   = NULL;
    INT19_tree   = NULL;
    FLOAT20_tree   = NULL;

    stream_VARIABLE   = NULL;
    #define CREATE_stream_VARIABLE  if (stream_VARIABLE == NULL) {stream_VARIABLE = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token VARIABLE"); } 
    stream_STRING   = NULL;
    #define CREATE_stream_STRING  if (stream_STRING == NULL) {stream_STRING = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token STRING"); } 

    retval.tree  = NULL;
    {
        {
            //  VerbQueryLanguage.g:70:2: ( VARIABLE -> ^( NODE_VARIABLE VARIABLE ) | STRING -> ^( NODE_STRING STRING ) | INT | FLOAT )
            
            ANTLR3_UINT32 alt6;

            alt6=4;

            switch ( LA(1) ) 
            {
            case VARIABLE:
            	{
            		alt6=1;
            	}
                break;
            case STRING:
            	{
            		alt6=2;
            	}
                break;
            case INT:
            	{
            		alt6=3;
            	}
                break;
            case FLOAT:
            	{
            		alt6=4;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 6;
                EXCEPTION->state        = 0;


                goto rulevalueEx;
            }

            switch (alt6) 
            {
        	case 1:
        	    // VerbQueryLanguage.g:70:4: VARIABLE
        	    {
        	        VARIABLE17 = (pANTLR3_COMMON_TOKEN) MATCHT(VARIABLE, &FOLLOW_VARIABLE_in_value419); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulevalueEx;
        	        }
        	         
        	        CREATE_stream_VARIABLE; stream_VARIABLE->add(stream_VARIABLE, VARIABLE17, NULL);


        	         
        	        /* AST REWRITE
        	         * elements          : VARIABLE
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 70:13: -> ^( NODE_VARIABLE VARIABLE )
        	        	{
        	        	    // VerbQueryLanguage.g:70:16: ^( NODE_VARIABLE VARIABLE )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, NODE_VARIABLE, (pANTLR3_UINT8)"NODE_VARIABLE"), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_VARIABLE == NULL ? NULL : stream_VARIABLE->nextNode(stream_VARIABLE));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguage.g:71:4: STRING
        	    {
        	        STRING18 = (pANTLR3_COMMON_TOKEN) MATCHT(STRING, &FOLLOW_STRING_in_value432); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulevalueEx;
        	        }
        	         
        	        CREATE_stream_STRING; stream_STRING->add(stream_STRING, STRING18, NULL);


        	         
        	        /* AST REWRITE
        	         * elements          : STRING
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 71:11: -> ^( NODE_STRING STRING )
        	        	{
        	        	    // VerbQueryLanguage.g:71:14: ^( NODE_STRING STRING )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, NODE_STRING, (pANTLR3_UINT8)"NODE_STRING"), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_STRING == NULL ? NULL : stream_STRING->nextNode(stream_STRING));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 3:
        	    // VerbQueryLanguage.g:72:4: INT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        INT19 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_value445); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulevalueEx;
        	        }

        	        INT19_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT19));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT19_tree);


        	    }
        	    break;
        	case 4:
        	    // VerbQueryLanguage.g:72:10: FLOAT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FLOAT20 = (pANTLR3_COMMON_TOKEN) MATCHT(FLOAT, &FOLLOW_FLOAT_in_value449); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulevalueEx;
        	        }

        	        FLOAT20_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, FLOAT20));
        	        ADAPTOR->addChild(ADAPTOR, root_0, FLOAT20_tree);


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulevalueEx; /* Prevent compiler warnings */
    rulevalueEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_VARIABLE != NULL) stream_VARIABLE->free(stream_VARIABLE);
        if (stream_STRING != NULL) stream_STRING->free(stream_STRING);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end value */

/** 
 * $ANTLR start function
 * VerbQueryLanguage.g:75:1: function : FUNCTION ( expr )? ( COMMA expr )* RPAREN -> ^( NODE_FUNCTION FUNCTION expr ( COMMA expr )* ) ;
 */
static VerbQueryLanguageParser_function_return
function(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_function_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    FUNCTION21;
    pANTLR3_COMMON_TOKEN    COMMA23;
    pANTLR3_COMMON_TOKEN    RPAREN25;
    VerbQueryLanguageParser_expr_return expr22;
    #undef	RETURN_TYPE_expr22
    #define	RETURN_TYPE_expr22 VerbQueryLanguageParser_expr_return

    VerbQueryLanguageParser_expr_return expr24;
    #undef	RETURN_TYPE_expr24
    #define	RETURN_TYPE_expr24 VerbQueryLanguageParser_expr_return

    pANTLR3_BASE_TREE FUNCTION21_tree;
    pANTLR3_BASE_TREE COMMA23_tree;
    pANTLR3_BASE_TREE RPAREN25_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_FUNCTION;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_RPAREN;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_COMMA;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */


    root_0 = NULL;

    FUNCTION21       = NULL;
    COMMA23       = NULL;
    RPAREN25       = NULL;
    expr22.tree = NULL;

    expr24.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    FUNCTION21_tree   = NULL;
    COMMA23_tree   = NULL;
    RPAREN25_tree   = NULL;

    stream_FUNCTION   = NULL;
    #define CREATE_stream_FUNCTION  if (stream_FUNCTION == NULL) {stream_FUNCTION = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token FUNCTION"); } 
    stream_RPAREN   = NULL;
    #define CREATE_stream_RPAREN  if (stream_RPAREN == NULL) {stream_RPAREN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token RPAREN"); } 
    stream_COMMA   = NULL;
    #define CREATE_stream_COMMA  if (stream_COMMA == NULL) {stream_COMMA = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token COMMA"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:76:2: ( FUNCTION ( expr )? ( COMMA expr )* RPAREN -> ^( NODE_FUNCTION FUNCTION expr ( COMMA expr )* ) )
        // VerbQueryLanguage.g:76:4: FUNCTION ( expr )? ( COMMA expr )* RPAREN
        {
            FUNCTION21 = (pANTLR3_COMMON_TOKEN) MATCHT(FUNCTION, &FOLLOW_FUNCTION_in_function460); 
            if  (HASEXCEPTION())
            {
                goto rulefunctionEx;
            }
             
            CREATE_stream_FUNCTION; stream_FUNCTION->add(stream_FUNCTION, FUNCTION21, NULL);


            // VerbQueryLanguage.g:76:13: ( expr )?
            {
                int alt7=2;
                switch ( LA(1) ) 
                {
                    case AT:
                    case NOT:
                    case LPAREN:
                    case PATH:
                    case VARIABLE:
                    case STRING:
                    case INT:
                    case FLOAT:
                    case FUNCTION:
                    case AXIS:
                    	{
                    		alt7=1;
                    	}
                        break;
                }

                switch (alt7) 
                {
            	case 1:
            	    // VerbQueryLanguage.g:76:13: expr
            	    {
            	        FOLLOWPUSH(FOLLOW_expr_in_function462);
            	        expr22=expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunctionEx;
            	        }

            	        CREATE_stream_expr; stream_expr->add(stream_expr, expr22.tree, NULL);

            	    }
            	    break;

                }
            }

            // VerbQueryLanguage.g:76:19: ( COMMA expr )*

            for (;;)
            {
                int alt8=2;
                switch ( LA(1) ) 
                {
                case COMMA:
                	{
                		alt8=1;
                	}
                    break;

                }

                switch (alt8) 
                {
            	case 1:
            	    // VerbQueryLanguage.g:76:20: COMMA expr
            	    {
            	        COMMA23 = (pANTLR3_COMMON_TOKEN) MATCHT(COMMA, &FOLLOW_COMMA_in_function466); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunctionEx;
            	        }
            	         
            	        CREATE_stream_COMMA; stream_COMMA->add(stream_COMMA, COMMA23, NULL);

            	        FOLLOWPUSH(FOLLOW_expr_in_function468);
            	        expr24=expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunctionEx;
            	        }

            	        CREATE_stream_expr; stream_expr->add(stream_expr, expr24.tree, NULL);

            	    }
            	    break;

            	default:
            	    goto loop8;	/* break out of the loop */
            	    break;
                }
            }
            loop8: ; /* Jump out to here if this rule does not match */

            RPAREN25 = (pANTLR3_COMMON_TOKEN) MATCHT(RPAREN, &FOLLOW_RPAREN_in_function472); 
            if  (HASEXCEPTION())
            {
                goto rulefunctionEx;
            }
             
            CREATE_stream_RPAREN; stream_RPAREN->add(stream_RPAREN, RPAREN25, NULL);


             
            /* AST REWRITE
             * elements          : expr, expr, COMMA, FUNCTION
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 76:40: -> ^( NODE_FUNCTION FUNCTION expr ( COMMA expr )* )
            	{
            	    // VerbQueryLanguage.g:76:43: ^( NODE_FUNCTION FUNCTION expr ( COMMA expr )* )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, NODE_FUNCTION, (pANTLR3_UINT8)"NODE_FUNCTION"), root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_FUNCTION == NULL ? NULL : stream_FUNCTION->nextNode(stream_FUNCTION));
            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));
            	        // VerbQueryLanguage.g:76:73: ( COMMA expr )*
            	        {
            	        	while ( (stream_expr != NULL && stream_expr->hasNext(stream_expr)) || (stream_COMMA != NULL && stream_COMMA->hasNext(stream_COMMA))  )
            	        	{
            	        		ADAPTOR->addChild(ADAPTOR, root_1, stream_COMMA == NULL ? NULL : stream_COMMA->nextNode(stream_COMMA));
            	        		ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

            	        	}
            	        	if (stream_expr != NULL) stream_expr->reset(stream_expr);
            	        	if (stream_COMMA != NULL) stream_COMMA->reset(stream_COMMA);

            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}

            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulefunctionEx; /* Prevent compiler warnings */
    rulefunctionEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_FUNCTION != NULL) stream_FUNCTION->free(stream_FUNCTION);
        if (stream_RPAREN != NULL) stream_RPAREN->free(stream_RPAREN);
        if (stream_COMMA != NULL) stream_COMMA->free(stream_COMMA);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end function */

/** 
 * $ANTLR start path
 * VerbQueryLanguage.g:79:1: path : ( (v= PATH | v= AXIS ) ( predicate )* -> ^( NODE_PATH $v ( predicate )* ) | AT path -> ^( AT path ) );
 */
static VerbQueryLanguageParser_path_return
path(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_path_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    v;
    pANTLR3_COMMON_TOKEN    AT27;
    VerbQueryLanguageParser_predicate_return predicate26;
    #undef	RETURN_TYPE_predicate26
    #define	RETURN_TYPE_predicate26 VerbQueryLanguageParser_predicate_return

    VerbQueryLanguageParser_path_return path28;
    #undef	RETURN_TYPE_path28
    #define	RETURN_TYPE_path28 VerbQueryLanguageParser_path_return

    pANTLR3_BASE_TREE v_tree;
    pANTLR3_BASE_TREE AT27_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_AT;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_AXIS;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_PATH;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_predicate;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_path;
    /* Initialize rule variables
     */


    root_0 = NULL;

    v       = NULL;
    AT27       = NULL;
    predicate26.tree = NULL;

    path28.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    v_tree   = NULL;
    AT27_tree   = NULL;

    stream_AT   = NULL;
    #define CREATE_stream_AT  if (stream_AT == NULL) {stream_AT = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token AT"); } 
    stream_AXIS   = NULL;
    #define CREATE_stream_AXIS  if (stream_AXIS == NULL) {stream_AXIS = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token AXIS"); } 
    stream_PATH   = NULL;
    #define CREATE_stream_PATH  if (stream_PATH == NULL) {stream_PATH = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token PATH"); } 
    stream_predicate   = NULL;
    #define CREATE_stream_predicate  if (stream_predicate == NULL) {stream_predicate = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule predicate"); }
    stream_path   = NULL;
    #define CREATE_stream_path  if (stream_path == NULL) {stream_path = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule path"); }

    retval.tree  = NULL;
    {
        {
            //  VerbQueryLanguage.g:80:2: ( (v= PATH | v= AXIS ) ( predicate )* -> ^( NODE_PATH $v ( predicate )* ) | AT path -> ^( AT path ) )
            
            ANTLR3_UINT32 alt11;

            alt11=2;

            switch ( LA(1) ) 
            {
            case PATH:
            case AXIS:
            	{
            		alt11=1;
            	}
                break;
            case AT:
            	{
            		alt11=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 11;
                EXCEPTION->state        = 0;


                goto rulepathEx;
            }

            switch (alt11) 
            {
        	case 1:
        	    // VerbQueryLanguage.g:80:4: (v= PATH | v= AXIS ) ( predicate )*
        	    {

        	        // VerbQueryLanguage.g:80:4: (v= PATH | v= AXIS )
        	        {
        	            int alt9=2;
        	            switch ( LA(1) ) 
        	            {
        	            case PATH:
        	            	{
        	            		alt9=1;
        	            	}
        	                break;
        	            case AXIS:
        	            	{
        	            		alt9=2;
        	            	}
        	                break;

        	            default:
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	                EXCEPTION->message      = (void *)"";
        	                EXCEPTION->decisionNum  = 9;
        	                EXCEPTION->state        = 0;


        	                goto rulepathEx;
        	            }

        	            switch (alt9) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguage.g:80:5: v= PATH
        	        	    {
        	        	        v = (pANTLR3_COMMON_TOKEN) MATCHT(PATH, &FOLLOW_PATH_in_path504); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulepathEx;
        	        	        }
        	        	         
        	        	        CREATE_stream_PATH; stream_PATH->add(stream_PATH, v, NULL);


        	        	    }
        	        	    break;
        	        	case 2:
        	        	    // VerbQueryLanguage.g:80:14: v= AXIS
        	        	    {
        	        	        v = (pANTLR3_COMMON_TOKEN) MATCHT(AXIS, &FOLLOW_AXIS_in_path510); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulepathEx;
        	        	        }
        	        	         
        	        	        CREATE_stream_AXIS; stream_AXIS->add(stream_AXIS, v, NULL);


        	        	    }
        	        	    break;

        	            }
        	        }

        	        // VerbQueryLanguage.g:80:22: ( predicate )*

        	        for (;;)
        	        {
        	            int alt10=2;
        	            switch ( LA(1) ) 
        	            {
        	            case LBRACKET:
        	            	{
        	            		alt10=1;
        	            	}
        	                break;

        	            }

        	            switch (alt10) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguage.g:80:22: predicate
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_predicate_in_path513);
        	        	        predicate26=predicate(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulepathEx;
        	        	        }

        	        	        CREATE_stream_predicate; stream_predicate->add(stream_predicate, predicate26.tree, NULL);

        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop10;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop10: ; /* Jump out to here if this rule does not match */


        	         
        	        /* AST REWRITE
        	         * elements          : predicate, v
        	         * token labels      : v
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_v;
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_v=antlr3RewriteRuleTOKENStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token v", v);
        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 80:33: -> ^( NODE_PATH $v ( predicate )* )
        	        	{
        	        	    // VerbQueryLanguage.g:80:36: ^( NODE_PATH $v ( predicate )* )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, NODE_PATH, (pANTLR3_UINT8)"NODE_PATH"), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_v == NULL ? NULL : stream_v->nextNode(stream_v));
        	        	        // VerbQueryLanguage.g:80:51: ( predicate )*
        	        	        {
        	        	        	while ( (stream_predicate != NULL && stream_predicate->hasNext(stream_predicate))  )
        	        	        	{
        	        	        		ADAPTOR->addChild(ADAPTOR, root_1, stream_predicate == NULL ? NULL : stream_predicate->nextTree(stream_predicate));

        	        	        	}
        	        	        	if (stream_predicate != NULL) stream_predicate->reset(stream_predicate);

        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_v != NULL) stream_v->free(stream_v); 
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguage.g:81:4: AT path
        	    {
        	        AT27 = (pANTLR3_COMMON_TOKEN) MATCHT(AT, &FOLLOW_AT_in_path531); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepathEx;
        	        }
        	         
        	        CREATE_stream_AT; stream_AT->add(stream_AT, AT27, NULL);

        	        FOLLOWPUSH(FOLLOW_path_in_path533);
        	        path28=path(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepathEx;
        	        }

        	        CREATE_stream_path; stream_path->add(stream_path, path28.tree, NULL);

        	         
        	        /* AST REWRITE
        	         * elements          : path, AT
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 81:12: -> ^( AT path )
        	        	{
        	        	    // VerbQueryLanguage.g:81:15: ^( AT path )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_AT == NULL ? NULL : stream_AT->nextNode(stream_AT), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_path == NULL ? NULL : stream_path->nextTree(stream_path));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulepathEx; /* Prevent compiler warnings */
    rulepathEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_AT != NULL) stream_AT->free(stream_AT);
        if (stream_AXIS != NULL) stream_AXIS->free(stream_AXIS);
        if (stream_PATH != NULL) stream_PATH->free(stream_PATH);
        if (stream_predicate != NULL) stream_predicate->free(stream_predicate);
        if (stream_path != NULL) stream_path->free(stream_path);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end path */

/** 
 * $ANTLR start predicate
 * VerbQueryLanguage.g:84:1: predicate : LBRACKET expr RBRACKET -> ^( NODE_PREDICATE expr ) ;
 */
static VerbQueryLanguageParser_predicate_return
predicate(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_predicate_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    LBRACKET29;
    pANTLR3_COMMON_TOKEN    RBRACKET31;
    VerbQueryLanguageParser_expr_return expr30;
    #undef	RETURN_TYPE_expr30
    #define	RETURN_TYPE_expr30 VerbQueryLanguageParser_expr_return

    pANTLR3_BASE_TREE LBRACKET29_tree;
    pANTLR3_BASE_TREE RBRACKET31_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_LBRACKET;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_RBRACKET;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */


    root_0 = NULL;

    LBRACKET29       = NULL;
    RBRACKET31       = NULL;
    expr30.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    LBRACKET29_tree   = NULL;
    RBRACKET31_tree   = NULL;

    stream_LBRACKET   = NULL;
    #define CREATE_stream_LBRACKET  if (stream_LBRACKET == NULL) {stream_LBRACKET = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token LBRACKET"); } 
    stream_RBRACKET   = NULL;
    #define CREATE_stream_RBRACKET  if (stream_RBRACKET == NULL) {stream_RBRACKET = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token RBRACKET"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:85:2: ( LBRACKET expr RBRACKET -> ^( NODE_PREDICATE expr ) )
        // VerbQueryLanguage.g:85:4: LBRACKET expr RBRACKET
        {
            LBRACKET29 = (pANTLR3_COMMON_TOKEN) MATCHT(LBRACKET, &FOLLOW_LBRACKET_in_predicate552); 
            if  (HASEXCEPTION())
            {
                goto rulepredicateEx;
            }
             
            CREATE_stream_LBRACKET; stream_LBRACKET->add(stream_LBRACKET, LBRACKET29, NULL);

            FOLLOWPUSH(FOLLOW_expr_in_predicate554);
            expr30=expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepredicateEx;
            }

            CREATE_stream_expr; stream_expr->add(stream_expr, expr30.tree, NULL);
            RBRACKET31 = (pANTLR3_COMMON_TOKEN) MATCHT(RBRACKET, &FOLLOW_RBRACKET_in_predicate556); 
            if  (HASEXCEPTION())
            {
                goto rulepredicateEx;
            }
             
            CREATE_stream_RBRACKET; stream_RBRACKET->add(stream_RBRACKET, RBRACKET31, NULL);


             
            /* AST REWRITE
             * elements          : expr
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 85:27: -> ^( NODE_PREDICATE expr )
            	{
            	    // VerbQueryLanguage.g:85:30: ^( NODE_PREDICATE expr )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, NODE_PREDICATE, (pANTLR3_UINT8)"NODE_PREDICATE"), root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}

            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepredicateEx; /* Prevent compiler warnings */
    rulepredicateEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_LBRACKET != NULL) stream_LBRACKET->free(stream_LBRACKET);
        if (stream_RBRACKET != NULL) stream_RBRACKET->free(stream_RBRACKET);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end predicate */

/** 
 * $ANTLR start operator
 * VerbQueryLanguage.g:88:1: operator : ( EQUALITY | EQUALITY_ALT | INEQUALITY | INEQUALITY_ALT | LESS | LTE | GREATER | GTE | AND | AND_ALT | OR | OR_ALT | XOR | XOR_ALT | ADD | SUB | MULT | SLASH | MOD );
 */
static VerbQueryLanguageParser_operator_return
operator(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_operator_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set32;

    pANTLR3_BASE_TREE set32_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    set32       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    set32_tree   = NULL;


    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:89:2: ( EQUALITY | EQUALITY_ALT | INEQUALITY | INEQUALITY_ALT | LESS | LTE | GREATER | GTE | AND | AND_ALT | OR | OR_ALT | XOR | XOR_ALT | ADD | SUB | MULT | SLASH | MOD )
        // VerbQueryLanguage.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            set32=(pANTLR3_COMMON_TOKEN)LT(1);
            if ( LA(1) == SLASH || ((LA(1) >= EQUALITY) && (LA(1) <= XOR)) || ((LA(1) >= ADD) && (LA(1) <= MOD)) || ((LA(1) >= AND_ALT) && (LA(1) <= XOR_ALT)) )
            {
                CONSUME();
                ADAPTOR->addChild(ADAPTOR, root_0, (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set32)));
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else 
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = &FOLLOW_set_in_operator0;
                RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_operator0);    goto ruleoperatorEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleoperatorEx; /* Prevent compiler warnings */
    ruleoperatorEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end operator */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
