/** \file
 *  This C source file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : VerbQueryLanguageTreeParser.g
 *     -                            On : 2010-06-10 11:23:13
 *     -           for the tree parser : VerbQueryLanguageTreeParserTreeParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


/* =============================================================================
 * This is what the grammar programmer asked us to put at the top of every file.
 */

#include "verbql.h"

/* End of Header action.
 * =============================================================================
 */
/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "VerbQueryLanguageTreeParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pVerbQueryLanguageTreeParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pVerbQueryLanguageTreeParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pVerbQueryLanguageTreeParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pVerbQueryLanguageTreeParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef	    BACKTRACKING
#undef      ADAPTOR
#undef	    RULEMEMO		
#undef		SEEK    
#undef		INDEX
#undef		DBG

#define	    PARSER							ctx->pTreeParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define	    INPUT							PARSER->ctnstream
#define		ISTREAM							INPUT->tnstream->istream
#define	    STRSTREAM						INPUT->tnstream
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							ISTREAM->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->tnstream->_LT(INPUT->tnstream, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         INPUT->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define		INDEX()							ISTREAM->index(ISTREAM)
#define		DBG								RECOGNIZER->debugger


#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   VerbQueryLanguageTreeParserTokenNames[41+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "NODE_PREDICATE",
        (pANTLR3_UINT8) "NODE_PATH",
        (pANTLR3_UINT8) "SLASH",
        (pANTLR3_UINT8) "SQL",
        (pANTLR3_UINT8) "AT",
        (pANTLR3_UINT8) "EQUALITY",
        (pANTLR3_UINT8) "EQUALITY_ALT",
        (pANTLR3_UINT8) "INEQUALITY",
        (pANTLR3_UINT8) "INEQUALITY_ALT",
        (pANTLR3_UINT8) "LESS",
        (pANTLR3_UINT8) "LTE",
        (pANTLR3_UINT8) "GREATER",
        (pANTLR3_UINT8) "GTE",
        (pANTLR3_UINT8) "AND",
        (pANTLR3_UINT8) "OR",
        (pANTLR3_UINT8) "XOR",
        (pANTLR3_UINT8) "NOT",
        (pANTLR3_UINT8) "ADD",
        (pANTLR3_UINT8) "SUB",
        (pANTLR3_UINT8) "MULT",
        (pANTLR3_UINT8) "MOD",
        (pANTLR3_UINT8) "IFTRUE",
        (pANTLR3_UINT8) "IFFALSE",
        (pANTLR3_UINT8) "LBRACKET",
        (pANTLR3_UINT8) "RBRACKET",
        (pANTLR3_UINT8) "LPAREN",
        (pANTLR3_UINT8) "RPAREN",
        (pANTLR3_UINT8) "COMMA",
        (pANTLR3_UINT8) "PATH",
        (pANTLR3_UINT8) "VARIABLE",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "FLOAT",
        (pANTLR3_UINT8) "FUNCTION",
        (pANTLR3_UINT8) "AXIS",
        (pANTLR3_UINT8) "AND_ALT",
        (pANTLR3_UINT8) "OR_ALT",
        (pANTLR3_UINT8) "XOR_ALT",
        (pANTLR3_UINT8) "ESC_SEQ",
        (pANTLR3_UINT8) "PATH_END",
        (pANTLR3_UINT8) "WS"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static pANTLR3_STRING	start    (pVerbQueryLanguageTreeParser ctx);
static pANTLR3_STRING	root_path    (pVerbQueryLanguageTreeParser ctx);
static void	predicate    (pVerbQueryLanguageTreeParser ctx);
static pANTLR3_STRING	expr    (pVerbQueryLanguageTreeParser ctx);
static pANTLR3_STRING	oper    (pVerbQueryLanguageTreeParser ctx);
static void	VerbQueryLanguageTreeParserFree(pVerbQueryLanguageTreeParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "VerbQueryLanguageTreeParser.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new VerbQueryLanguageTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pVerbQueryLanguageTreeParser
VerbQueryLanguageTreeParserNew   (pANTLR3_COMMON_TREE_NODE_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return VerbQueryLanguageTreeParserNewSSD(instream, NULL);
}

/** \brief Create a new VerbQueryLanguageTreeParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pVerbQueryLanguageTreeParser
VerbQueryLanguageTreeParserNewSSD   (pANTLR3_COMMON_TREE_NODE_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pVerbQueryLanguageTreeParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pVerbQueryLanguageTreeParser) ANTLR3_CALLOC(1, sizeof(VerbQueryLanguageTreeParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in VerbQueryLanguageTreeParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base Tree parser/recognizer, using the supplied tree node stream
     */
    ctx->pTreeParser		= antlr3TreeParserNewStream(ANTLR3_SIZE_HINT, instream, state);
    /* Install the implementation of our VerbQueryLanguageTreeParser interface
     */
    ctx->start	= start;
    ctx->root_path	= root_path;
    ctx->predicate	= predicate;
    ctx->expr	= expr;
    ctx->oper	= oper;
    ctx->free			= VerbQueryLanguageTreeParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */

        
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = VerbQueryLanguageTreeParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 VerbQueryLanguageTreeParserFree(pVerbQueryLanguageTreeParser ctx)
 {
    /* Free any scope memory
     */
    
        
	// Free this parser
	//
    ctx->pTreeParser->free(ctx->pTreeParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this tree parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return VerbQueryLanguageTreeParserTokenNames; 
}


      int VerbQueryLanguagePath = 0;

      int asBoolean(pANTLR3_STRING a) {
        double dummy;
        if (sscanf(a->chars, "%lf", &dummy)) return (dummy != 0);
        return strcmp(a->chars, "");
      }
      
      int asInt(pANTLR3_STRING a) {
        return atoi(a->chars);
      }
      
      double asNumber(pANTLR3_STRING a) {
        return strtod(a->chars, NULL);
      }

      int bothNumbers(pANTLR3_STRING a, pANTLR3_STRING b) {
        double dummy;
        return (sscanf(a->chars, "%lf", &dummy) && sscanf(b->chars, "%lf", &dummy));
      }

      pANTLR3_STRING booleanResponse(int t, pANTLR3_BASE_TREE e) {
        if (t) {
          return e->strFactory->newStr(e->strFactory, "1");
        } else {
          return e->strFactory->newStr(e->strFactory, "0");
        }
      }
      
      pANTLR3_STRING numberResponse(double t, pANTLR3_BASE_TREE e) {
        char buf[30];
        sprintf(buf, "%lg", t);
        return e->strFactory->newStr(e->strFactory, buf);
      }

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_root_path_in_start62  */
static	ANTLR3_BITWORD FOLLOW_root_path_in_start62_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_root_path_in_start62	= { FOLLOW_root_path_in_start62_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_start64  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_start64_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_start64	= { FOLLOW_EOF_in_start64_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_start76  */
static	ANTLR3_BITWORD FOLLOW_expr_in_start76_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_start76	= { FOLLOW_expr_in_start76_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_start78  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_start78_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_start78	= { FOLLOW_EOF_in_start78_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NODE_PATH_in_root_path103  */
static	ANTLR3_BITWORD FOLLOW_NODE_PATH_in_root_path103_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100000080) };
static  ANTLR3_BITSET_LIST FOLLOW_NODE_PATH_in_root_path103	= { FOLLOW_NODE_PATH_in_root_path103_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SQL_in_root_path115  */
static	ANTLR3_BITWORD FOLLOW_SQL_in_root_path115_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100000000) };
static  ANTLR3_BITSET_LIST FOLLOW_SQL_in_root_path115	= { FOLLOW_SQL_in_root_path115_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PATH_in_root_path128  */
static	ANTLR3_BITWORD FOLLOW_PATH_in_root_path128_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_PATH_in_root_path128	= { FOLLOW_PATH_in_root_path128_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_in_root_path140  */
static	ANTLR3_BITWORD FOLLOW_predicate_in_root_path140_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000010) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_in_root_path140	= { FOLLOW_predicate_in_root_path140_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_root_path153  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_root_path153_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_root_path153	= { FOLLOW_EOF_in_root_path153_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NODE_PREDICATE_in_predicate168  */
static	ANTLR3_BITWORD FOLLOW_NODE_PREDICATE_in_predicate168_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_NODE_PREDICATE_in_predicate168	= { FOLLOW_NODE_PREDICATE_in_predicate168_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_oper_in_expr187  */
static	ANTLR3_BITWORD FOLLOW_oper_in_expr187_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_oper_in_expr187	= { FOLLOW_oper_in_expr187_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_VARIABLE_in_expr199  */
static	ANTLR3_BITWORD FOLLOW_VARIABLE_in_expr199_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_VARIABLE_in_expr199	= { FOLLOW_VARIABLE_in_expr199_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_STRING_in_expr211  */
static	ANTLR3_BITWORD FOLLOW_STRING_in_expr211_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_STRING_in_expr211	= { FOLLOW_STRING_in_expr211_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FLOAT_in_expr223  */
static	ANTLR3_BITWORD FOLLOW_FLOAT_in_expr223_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_FLOAT_in_expr223	= { FOLLOW_FLOAT_in_expr223_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_expr235  */
static	ANTLR3_BITWORD FOLLOW_INT_in_expr235_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_expr235	= { FOLLOW_INT_in_expr235_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EQUALITY_in_oper263  */
static	ANTLR3_BITWORD FOLLOW_EQUALITY_in_oper263_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_EQUALITY_in_oper263	= { FOLLOW_EQUALITY_in_oper263_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EQUALITY_ALT_in_oper269  */
static	ANTLR3_BITWORD FOLLOW_EQUALITY_ALT_in_oper269_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_EQUALITY_ALT_in_oper269	= { FOLLOW_EQUALITY_ALT_in_oper269_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper274  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper274_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper274	= { FOLLOW_expr_in_oper274_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper278  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper278_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper278	= { FOLLOW_expr_in_oper278_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INEQUALITY_in_oper294  */
static	ANTLR3_BITWORD FOLLOW_INEQUALITY_in_oper294_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_INEQUALITY_in_oper294	= { FOLLOW_INEQUALITY_in_oper294_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INEQUALITY_ALT_in_oper300  */
static	ANTLR3_BITWORD FOLLOW_INEQUALITY_ALT_in_oper300_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_INEQUALITY_ALT_in_oper300	= { FOLLOW_INEQUALITY_ALT_in_oper300_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper305  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper305_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper305	= { FOLLOW_expr_in_oper305_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper309  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper309_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper309	= { FOLLOW_expr_in_oper309_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LESS_in_oper324  */
static	ANTLR3_BITWORD FOLLOW_LESS_in_oper324_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_LESS_in_oper324	= { FOLLOW_LESS_in_oper324_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper328  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper328_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper328	= { FOLLOW_expr_in_oper328_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper332  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper332_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper332	= { FOLLOW_expr_in_oper332_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LTE_in_oper347  */
static	ANTLR3_BITWORD FOLLOW_LTE_in_oper347_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_LTE_in_oper347	= { FOLLOW_LTE_in_oper347_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper351  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper351_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper351	= { FOLLOW_expr_in_oper351_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper355  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper355_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper355	= { FOLLOW_expr_in_oper355_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_GREATER_in_oper370  */
static	ANTLR3_BITWORD FOLLOW_GREATER_in_oper370_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_GREATER_in_oper370	= { FOLLOW_GREATER_in_oper370_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper374  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper374_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper374	= { FOLLOW_expr_in_oper374_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper378  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper378_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper378	= { FOLLOW_expr_in_oper378_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_GTE_in_oper393  */
static	ANTLR3_BITWORD FOLLOW_GTE_in_oper393_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_GTE_in_oper393	= { FOLLOW_GTE_in_oper393_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper397  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper397_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper397	= { FOLLOW_expr_in_oper397_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper401  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper401_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper401	= { FOLLOW_expr_in_oper401_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AND_in_oper417  */
static	ANTLR3_BITWORD FOLLOW_AND_in_oper417_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_AND_in_oper417	= { FOLLOW_AND_in_oper417_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AND_ALT_in_oper423  */
static	ANTLR3_BITWORD FOLLOW_AND_ALT_in_oper423_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_AND_ALT_in_oper423	= { FOLLOW_AND_ALT_in_oper423_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper428  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper428_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper428	= { FOLLOW_expr_in_oper428_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper432  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper432_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper432	= { FOLLOW_expr_in_oper432_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OR_in_oper448  */
static	ANTLR3_BITWORD FOLLOW_OR_in_oper448_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_OR_in_oper448	= { FOLLOW_OR_in_oper448_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_OR_ALT_in_oper454  */
static	ANTLR3_BITWORD FOLLOW_OR_ALT_in_oper454_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_OR_ALT_in_oper454	= { FOLLOW_OR_ALT_in_oper454_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper459  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper459_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper459	= { FOLLOW_expr_in_oper459_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper463  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper463_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper463	= { FOLLOW_expr_in_oper463_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_XOR_in_oper479  */
static	ANTLR3_BITWORD FOLLOW_XOR_in_oper479_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_XOR_in_oper479	= { FOLLOW_XOR_in_oper479_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_XOR_ALT_in_oper485  */
static	ANTLR3_BITWORD FOLLOW_XOR_ALT_in_oper485_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_XOR_ALT_in_oper485	= { FOLLOW_XOR_ALT_in_oper485_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper490  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper490_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper490	= { FOLLOW_expr_in_oper490_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper494  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper494_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper494	= { FOLLOW_expr_in_oper494_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_ADD_in_oper509  */
static	ANTLR3_BITWORD FOLLOW_ADD_in_oper509_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_ADD_in_oper509	= { FOLLOW_ADD_in_oper509_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper513  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper513_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper513	= { FOLLOW_expr_in_oper513_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper517  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper517_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper517	= { FOLLOW_expr_in_oper517_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SUB_in_oper532  */
static	ANTLR3_BITWORD FOLLOW_SUB_in_oper532_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_SUB_in_oper532	= { FOLLOW_SUB_in_oper532_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper536  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper536_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper536	= { FOLLOW_expr_in_oper536_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper540  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper540_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper540	= { FOLLOW_expr_in_oper540_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MULT_in_oper555  */
static	ANTLR3_BITWORD FOLLOW_MULT_in_oper555_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_MULT_in_oper555	= { FOLLOW_MULT_in_oper555_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper559  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper559_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper559	= { FOLLOW_expr_in_oper559_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper563  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper563_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper563	= { FOLLOW_expr_in_oper563_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SLASH_in_oper578  */
static	ANTLR3_BITWORD FOLLOW_SLASH_in_oper578_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_SLASH_in_oper578	= { FOLLOW_SLASH_in_oper578_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper582  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper582_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper582	= { FOLLOW_expr_in_oper582_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper586  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper586_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper586	= { FOLLOW_expr_in_oper586_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_MOD_in_oper601  */
static	ANTLR3_BITWORD FOLLOW_MOD_in_oper601_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000004) };
static  ANTLR3_BITSET_LIST FOLLOW_MOD_in_oper601	= { FOLLOW_MOD_in_oper601_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper605  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper605_bits[]	= { ANTLR3_UINT64_LIT(0x0000039E01EFFE40) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper605	= { FOLLOW_expr_in_oper605_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_oper609  */
static	ANTLR3_BITWORD FOLLOW_expr_in_oper609_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000008) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_oper609	= { FOLLOW_expr_in_oper609_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start start
 * VerbQueryLanguageTreeParser.g:53:1: start returns [ pANTLR3_STRING result ] : ( root_path EOF | expr EOF );
 */
static pANTLR3_STRING
start(pVerbQueryLanguageTreeParser ctx)
{   
    pANTLR3_STRING result = NULL;

    pANTLR3_STRING root_path1;
    #undef	RETURN_TYPE_root_path1
    #define	RETURN_TYPE_root_path1 pANTLR3_STRING

    pANTLR3_STRING expr2;
    #undef	RETURN_TYPE_expr2
    #define	RETURN_TYPE_expr2 pANTLR3_STRING

    /* Initialize rule variables
     */


    root_path1 = NULL;
    expr2 = NULL;

    {
        {
            //  VerbQueryLanguageTreeParser.g:55:3: ( root_path EOF | expr EOF )
            
            ANTLR3_UINT32 alt1;

            alt1=2;

            switch ( LA(1) ) 
            {
            case NODE_PATH:
            	{
            		alt1=1;
            	}
                break;
            case SLASH:
            case EQUALITY:
            case EQUALITY_ALT:
            case INEQUALITY:
            case INEQUALITY_ALT:
            case LESS:
            case LTE:
            case GREATER:
            case GTE:
            case AND:
            case OR:
            case XOR:
            case ADD:
            case SUB:
            case MULT:
            case MOD:
            case VARIABLE:
            case STRING:
            case INT:
            case FLOAT:
            case AND_ALT:
            case OR_ALT:
            case XOR_ALT:
            	{
            		alt1=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 1;
                EXCEPTION->state        = 0;


                goto rulestartEx;
            }

            switch (alt1) 
            {
        	case 1:
        	    // VerbQueryLanguageTreeParser.g:55:5: root_path EOF
        	    {
        	        FOLLOWPUSH(FOLLOW_root_path_in_start62);
        	        root_path1=root_path(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestartEx;
        	        }

        	         MATCHT(EOF, &FOLLOW_EOF_in_start64); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestartEx;
        	        }

        	        {

        	                  VerbQueryLanguagePath = 1;
        	                  result= root_path1;
        	                
        	        }

        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguageTreeParser.g:60:5: expr EOF
        	    {
        	        FOLLOWPUSH(FOLLOW_expr_in_start76);
        	        expr2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestartEx;
        	        }

        	         MATCHT(EOF, &FOLLOW_EOF_in_start78); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulestartEx;
        	        }

        	        {

        	                  VerbQueryLanguagePath = 0;
        	                  result= expr2;
        	                
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulestartEx; /* Prevent compiler warnings */
    rulestartEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return result;
}
/* $ANTLR end start */

/** 
 * $ANTLR start root_path
 * VerbQueryLanguageTreeParser.g:67:1: root_path returns [ pANTLR3_STRING result ] : NODE_PATH ( SQL )? PATH ( predicate )* EOF ;
 */
static pANTLR3_STRING
root_path(pVerbQueryLanguageTreeParser ctx)
{   
    pANTLR3_STRING result = NULL;

    pANTLR3_BASE_TREE    NODE_PATH3;
    pANTLR3_BASE_TREE    PATH4;

    /* Initialize rule variables
     */


    NODE_PATH3       = NULL;
    PATH4       = NULL;

    {
        // VerbQueryLanguageTreeParser.g:69:3: ( NODE_PATH ( SQL )? PATH ( predicate )* EOF )
        // VerbQueryLanguageTreeParser.g:69:5: NODE_PATH ( SQL )? PATH ( predicate )* EOF
        {
            NODE_PATH3 = (pANTLR3_BASE_TREE) MATCHT(NODE_PATH, &FOLLOW_NODE_PATH_in_root_path103); 
            if  (HASEXCEPTION())
            {
                goto ruleroot_pathEx;
            }

            {

                      result= (NODE_PATH3->getText(NODE_PATH3));
                    
            }

            // VerbQueryLanguageTreeParser.g:73:5: ( SQL )?
            {
                int alt2=2;
                switch ( LA(1) ) 
                {
                    case SQL:
                    	{
                    		alt2=1;
                    	}
                        break;
                }

                switch (alt2) 
                {
            	case 1:
            	    // VerbQueryLanguageTreeParser.g:73:5: SQL
            	    {
            	         MATCHT(SQL, &FOLLOW_SQL_in_root_path115); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleroot_pathEx;
            	        }


            	    }
            	    break;

                }
            }
            {

                      printf("got a sql\n");
                    
            }
            PATH4 = (pANTLR3_BASE_TREE) MATCHT(PATH, &FOLLOW_PATH_in_root_path128); 
            if  (HASEXCEPTION())
            {
                goto ruleroot_pathEx;
            }

            {

                      result= (PATH4->getText(PATH4));
                    
            }

            // VerbQueryLanguageTreeParser.g:81:5: ( predicate )*

            for (;;)
            {
                int alt3=2;
                switch ( LA(1) ) 
                {
                case NODE_PREDICATE:
                	{
                		alt3=1;
                	}
                    break;

                }

                switch (alt3) 
                {
            	case 1:
            	    // VerbQueryLanguageTreeParser.g:81:5: predicate
            	    {
            	        FOLLOWPUSH(FOLLOW_predicate_in_root_path140);
            	        predicate(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto ruleroot_pathEx;
            	        }


            	    }
            	    break;

            	default:
            	    goto loop3;	/* break out of the loop */
            	    break;
                }
            }
            loop3: ; /* Jump out to here if this rule does not match */

            {

                      printf("got a pred\n");
                    
            }
             MATCHT(EOF, &FOLLOW_EOF_in_root_path153); 
            if  (HASEXCEPTION())
            {
                goto ruleroot_pathEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleroot_pathEx; /* Prevent compiler warnings */
    ruleroot_pathEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return result;
}
/* $ANTLR end root_path */

/** 
 * $ANTLR start predicate
 * VerbQueryLanguageTreeParser.g:88:1: predicate : NODE_PREDICATE ;
 */
static void
predicate(pVerbQueryLanguageTreeParser ctx)
{   
    /* Initialize rule variables
     */


    {
        // VerbQueryLanguageTreeParser.g:89:3: ( NODE_PREDICATE )
        // VerbQueryLanguageTreeParser.g:89:5: NODE_PREDICATE
        {
             MATCHT(NODE_PREDICATE, &FOLLOW_NODE_PREDICATE_in_predicate168); 
            if  (HASEXCEPTION())
            {
                goto rulepredicateEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepredicateEx; /* Prevent compiler warnings */
    rulepredicateEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return ;
}
/* $ANTLR end predicate */

/** 
 * $ANTLR start expr
 * VerbQueryLanguageTreeParser.g:92:1: expr returns [ pANTLR3_STRING result ] : ( oper | VARIABLE | STRING | FLOAT | INT );
 */
static pANTLR3_STRING
expr(pVerbQueryLanguageTreeParser ctx)
{   
    pANTLR3_STRING result = NULL;

    pANTLR3_BASE_TREE    VARIABLE6;
    pANTLR3_BASE_TREE    STRING7;
    pANTLR3_BASE_TREE    FLOAT8;
    pANTLR3_BASE_TREE    INT9;
    pANTLR3_STRING oper5;
    #undef	RETURN_TYPE_oper5
    #define	RETURN_TYPE_oper5 pANTLR3_STRING

    /* Initialize rule variables
     */


    VARIABLE6       = NULL;
    STRING7       = NULL;
    FLOAT8       = NULL;
    INT9       = NULL;
    oper5 = NULL;

    {
        {
            //  VerbQueryLanguageTreeParser.g:94:3: ( oper | VARIABLE | STRING | FLOAT | INT )
            
            ANTLR3_UINT32 alt4;

            alt4=5;

            switch ( LA(1) ) 
            {
            case SLASH:
            case EQUALITY:
            case EQUALITY_ALT:
            case INEQUALITY:
            case INEQUALITY_ALT:
            case LESS:
            case LTE:
            case GREATER:
            case GTE:
            case AND:
            case OR:
            case XOR:
            case ADD:
            case SUB:
            case MULT:
            case MOD:
            case AND_ALT:
            case OR_ALT:
            case XOR_ALT:
            	{
            		alt4=1;
            	}
                break;
            case VARIABLE:
            	{
            		alt4=2;
            	}
                break;
            case STRING:
            	{
            		alt4=3;
            	}
                break;
            case FLOAT:
            	{
            		alt4=4;
            	}
                break;
            case INT:
            	{
            		alt4=5;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 4;
                EXCEPTION->state        = 0;


                goto ruleexprEx;
            }

            switch (alt4) 
            {
        	case 1:
        	    // VerbQueryLanguageTreeParser.g:94:5: oper
        	    {
        	        FOLLOWPUSH(FOLLOW_oper_in_expr187);
        	        oper5=oper(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {

        	                  result= oper5;
        	                
        	        }

        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguageTreeParser.g:98:5: VARIABLE
        	    {
        	        VARIABLE6 = (pANTLR3_BASE_TREE) MATCHT(VARIABLE, &FOLLOW_VARIABLE_in_expr199); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {

        	                  result= (VARIABLE6->getText(VARIABLE6));
        	                
        	        }

        	    }
        	    break;
        	case 3:
        	    // VerbQueryLanguageTreeParser.g:102:5: STRING
        	    {
        	        STRING7 = (pANTLR3_BASE_TREE) MATCHT(STRING, &FOLLOW_STRING_in_expr211); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {

        	                  result= (STRING7->getText(STRING7))->subString((STRING7->getText(STRING7)), 1, strlen((STRING7->getText(STRING7))->chars) - 1);
        	                
        	        }

        	    }
        	    break;
        	case 4:
        	    // VerbQueryLanguageTreeParser.g:106:5: FLOAT
        	    {
        	        FLOAT8 = (pANTLR3_BASE_TREE) MATCHT(FLOAT, &FOLLOW_FLOAT_in_expr223); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {

        	                  result= (FLOAT8->getText(FLOAT8));
        	                
        	        }

        	    }
        	    break;
        	case 5:
        	    // VerbQueryLanguageTreeParser.g:110:5: INT
        	    {
        	        INT9 = (pANTLR3_BASE_TREE) MATCHT(INT, &FOLLOW_INT_in_expr235); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        {

        	                  result= (INT9->getText(INT9));
        	                
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return result;
}
/* $ANTLR end expr */

/** 
 * $ANTLR start oper
 * VerbQueryLanguageTreeParser.g:116:1: oper returns [ pANTLR3_STRING result ] : ( ^( (e= EQUALITY | e= EQUALITY_ALT ) e1= expr e2= expr ) | ^( (e= INEQUALITY | e= INEQUALITY_ALT ) e1= expr e2= expr ) | ^(e= LESS e1= expr e2= expr ) | ^(e= LTE e1= expr e2= expr ) | ^(e= GREATER e1= expr e2= expr ) | ^(e= GTE e1= expr e2= expr ) | ^( (e= AND | e= AND_ALT ) e1= expr e2= expr ) | ^( (e= OR | e= OR_ALT ) e1= expr e2= expr ) | ^( (e= XOR | e= XOR_ALT ) e1= expr e2= expr ) | ^(e= ADD e1= expr e2= expr ) | ^(e= SUB e1= expr e2= expr ) | ^(e= MULT e1= expr e2= expr ) | ^(e= SLASH e1= expr e2= expr ) | ^(e= MOD e1= expr e2= expr ) );
 */
static pANTLR3_STRING
oper(pVerbQueryLanguageTreeParser ctx)
{   
    pANTLR3_STRING result = NULL;

    pANTLR3_BASE_TREE    e;
    pANTLR3_STRING e1;
    #undef	RETURN_TYPE_e1
    #define	RETURN_TYPE_e1 pANTLR3_STRING

    pANTLR3_STRING e2;
    #undef	RETURN_TYPE_e2
    #define	RETURN_TYPE_e2 pANTLR3_STRING

    /* Initialize rule variables
     */


    e       = NULL;
    e1 = NULL;
    e2 = NULL;

    {
        {
            //  VerbQueryLanguageTreeParser.g:118:2: ( ^( (e= EQUALITY | e= EQUALITY_ALT ) e1= expr e2= expr ) | ^( (e= INEQUALITY | e= INEQUALITY_ALT ) e1= expr e2= expr ) | ^(e= LESS e1= expr e2= expr ) | ^(e= LTE e1= expr e2= expr ) | ^(e= GREATER e1= expr e2= expr ) | ^(e= GTE e1= expr e2= expr ) | ^( (e= AND | e= AND_ALT ) e1= expr e2= expr ) | ^( (e= OR | e= OR_ALT ) e1= expr e2= expr ) | ^( (e= XOR | e= XOR_ALT ) e1= expr e2= expr ) | ^(e= ADD e1= expr e2= expr ) | ^(e= SUB e1= expr e2= expr ) | ^(e= MULT e1= expr e2= expr ) | ^(e= SLASH e1= expr e2= expr ) | ^(e= MOD e1= expr e2= expr ) )
            
            ANTLR3_UINT32 alt10;

            alt10=14;

            switch ( LA(1) ) 
            {
            case EQUALITY:
            case EQUALITY_ALT:
            	{
            		alt10=1;
            	}
                break;
            case INEQUALITY:
            case INEQUALITY_ALT:
            	{
            		alt10=2;
            	}
                break;
            case LESS:
            	{
            		alt10=3;
            	}
                break;
            case LTE:
            	{
            		alt10=4;
            	}
                break;
            case GREATER:
            	{
            		alt10=5;
            	}
                break;
            case GTE:
            	{
            		alt10=6;
            	}
                break;
            case AND:
            case AND_ALT:
            	{
            		alt10=7;
            	}
                break;
            case OR:
            case OR_ALT:
            	{
            		alt10=8;
            	}
                break;
            case XOR:
            case XOR_ALT:
            	{
            		alt10=9;
            	}
                break;
            case ADD:
            	{
            		alt10=10;
            	}
                break;
            case SUB:
            	{
            		alt10=11;
            	}
                break;
            case MULT:
            	{
            		alt10=12;
            	}
                break;
            case SLASH:
            	{
            		alt10=13;
            	}
                break;
            case MOD:
            	{
            		alt10=14;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 10;
                EXCEPTION->state        = 0;


                goto ruleoperEx;
            }

            switch (alt10) 
            {
        	case 1:
        	    // VerbQueryLanguageTreeParser.g:118:4: ^( (e= EQUALITY | e= EQUALITY_ALT ) e1= expr e2= expr )
        	    {

        	        // VerbQueryLanguageTreeParser.g:118:6: (e= EQUALITY | e= EQUALITY_ALT )
        	        {
        	            int alt5=2;
        	            switch ( LA(1) ) 
        	            {
        	            case EQUALITY:
        	            	{
        	            		alt5=1;
        	            	}
        	                break;
        	            case EQUALITY_ALT:
        	            	{
        	            		alt5=2;
        	            	}
        	                break;

        	            default:
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	                EXCEPTION->message      = (void *)"";
        	                EXCEPTION->decisionNum  = 5;
        	                EXCEPTION->state        = 0;


        	                goto ruleoperEx;
        	            }

        	            switch (alt5) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguageTreeParser.g:118:7: e= EQUALITY
        	        	    {
        	        	        e = (pANTLR3_BASE_TREE) MATCHT(EQUALITY, &FOLLOW_EQUALITY_in_oper263); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleoperEx;
        	        	        }


        	        	    }
        	        	    break;
        	        	case 2:
        	        	    // VerbQueryLanguageTreeParser.g:118:20: e= EQUALITY_ALT
        	        	    {
        	        	        e = (pANTLR3_BASE_TREE) MATCHT(EQUALITY_ALT, &FOLLOW_EQUALITY_ALT_in_oper269); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleoperEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper274);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper278);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= booleanResponse((bothNumbers(e1, e2) ? asNumber(e1) == asNumber(e2) : !strcmp(e1->chars, e2->chars)), e);
        	                
        	        }

        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguageTreeParser.g:122:4: ^( (e= INEQUALITY | e= INEQUALITY_ALT ) e1= expr e2= expr )
        	    {

        	        // VerbQueryLanguageTreeParser.g:122:6: (e= INEQUALITY | e= INEQUALITY_ALT )
        	        {
        	            int alt6=2;
        	            switch ( LA(1) ) 
        	            {
        	            case INEQUALITY:
        	            	{
        	            		alt6=1;
        	            	}
        	                break;
        	            case INEQUALITY_ALT:
        	            	{
        	            		alt6=2;
        	            	}
        	                break;

        	            default:
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	                EXCEPTION->message      = (void *)"";
        	                EXCEPTION->decisionNum  = 6;
        	                EXCEPTION->state        = 0;


        	                goto ruleoperEx;
        	            }

        	            switch (alt6) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguageTreeParser.g:122:7: e= INEQUALITY
        	        	    {
        	        	        e = (pANTLR3_BASE_TREE) MATCHT(INEQUALITY, &FOLLOW_INEQUALITY_in_oper294); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleoperEx;
        	        	        }


        	        	    }
        	        	    break;
        	        	case 2:
        	        	    // VerbQueryLanguageTreeParser.g:122:22: e= INEQUALITY_ALT
        	        	    {
        	        	        e = (pANTLR3_BASE_TREE) MATCHT(INEQUALITY_ALT, &FOLLOW_INEQUALITY_ALT_in_oper300); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleoperEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper305);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper309);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= booleanResponse((bothNumbers(e1, e2) ? asNumber(e1) != asNumber(e2) : strcmp(e1->chars, e2->chars)), e);
        	                
        	        }

        	    }
        	    break;
        	case 3:
        	    // VerbQueryLanguageTreeParser.g:126:4: ^(e= LESS e1= expr e2= expr )
        	    {
        	        e = (pANTLR3_BASE_TREE) MATCHT(LESS, &FOLLOW_LESS_in_oper324); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper328);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper332);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= booleanResponse((bothNumbers(e1, e2) ? asNumber(e1) < asNumber(e2) : strcmp(e1->chars, e2->chars) < 0), e);
        	                
        	        }

        	    }
        	    break;
        	case 4:
        	    // VerbQueryLanguageTreeParser.g:130:4: ^(e= LTE e1= expr e2= expr )
        	    {
        	        e = (pANTLR3_BASE_TREE) MATCHT(LTE, &FOLLOW_LTE_in_oper347); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper351);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper355);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= booleanResponse((bothNumbers(e1, e2) ? asNumber(e1) <= asNumber(e2) : strcmp(e1->chars, e2->chars) <= 0), e);
        	                
        	        }

        	    }
        	    break;
        	case 5:
        	    // VerbQueryLanguageTreeParser.g:134:4: ^(e= GREATER e1= expr e2= expr )
        	    {
        	        e = (pANTLR3_BASE_TREE) MATCHT(GREATER, &FOLLOW_GREATER_in_oper370); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper374);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper378);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= booleanResponse((bothNumbers(e1, e2) ? asNumber(e1) > asNumber(e2) : strcmp(e1->chars, e2->chars) > 0), e);
        	                
        	        }

        	    }
        	    break;
        	case 6:
        	    // VerbQueryLanguageTreeParser.g:138:4: ^(e= GTE e1= expr e2= expr )
        	    {
        	        e = (pANTLR3_BASE_TREE) MATCHT(GTE, &FOLLOW_GTE_in_oper393); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper397);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper401);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= booleanResponse((bothNumbers(e1, e2) ? asNumber(e1) >= asNumber(e2) : strcmp(e1->chars, e2->chars) >= 0), e);
        	                
        	        }

        	    }
        	    break;
        	case 7:
        	    // VerbQueryLanguageTreeParser.g:142:4: ^( (e= AND | e= AND_ALT ) e1= expr e2= expr )
        	    {

        	        // VerbQueryLanguageTreeParser.g:142:6: (e= AND | e= AND_ALT )
        	        {
        	            int alt7=2;
        	            switch ( LA(1) ) 
        	            {
        	            case AND:
        	            	{
        	            		alt7=1;
        	            	}
        	                break;
        	            case AND_ALT:
        	            	{
        	            		alt7=2;
        	            	}
        	                break;

        	            default:
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	                EXCEPTION->message      = (void *)"";
        	                EXCEPTION->decisionNum  = 7;
        	                EXCEPTION->state        = 0;


        	                goto ruleoperEx;
        	            }

        	            switch (alt7) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguageTreeParser.g:142:7: e= AND
        	        	    {
        	        	        e = (pANTLR3_BASE_TREE) MATCHT(AND, &FOLLOW_AND_in_oper417); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleoperEx;
        	        	        }


        	        	    }
        	        	    break;
        	        	case 2:
        	        	    // VerbQueryLanguageTreeParser.g:142:15: e= AND_ALT
        	        	    {
        	        	        e = (pANTLR3_BASE_TREE) MATCHT(AND_ALT, &FOLLOW_AND_ALT_in_oper423); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleoperEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper428);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper432);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= booleanResponse(asBoolean(e1) && asBoolean(e2), e);
        	                
        	        }

        	    }
        	    break;
        	case 8:
        	    // VerbQueryLanguageTreeParser.g:146:4: ^( (e= OR | e= OR_ALT ) e1= expr e2= expr )
        	    {

        	        // VerbQueryLanguageTreeParser.g:146:6: (e= OR | e= OR_ALT )
        	        {
        	            int alt8=2;
        	            switch ( LA(1) ) 
        	            {
        	            case OR:
        	            	{
        	            		alt8=1;
        	            	}
        	                break;
        	            case OR_ALT:
        	            	{
        	            		alt8=2;
        	            	}
        	                break;

        	            default:
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	                EXCEPTION->message      = (void *)"";
        	                EXCEPTION->decisionNum  = 8;
        	                EXCEPTION->state        = 0;


        	                goto ruleoperEx;
        	            }

        	            switch (alt8) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguageTreeParser.g:146:7: e= OR
        	        	    {
        	        	        e = (pANTLR3_BASE_TREE) MATCHT(OR, &FOLLOW_OR_in_oper448); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleoperEx;
        	        	        }


        	        	    }
        	        	    break;
        	        	case 2:
        	        	    // VerbQueryLanguageTreeParser.g:146:14: e= OR_ALT
        	        	    {
        	        	        e = (pANTLR3_BASE_TREE) MATCHT(OR_ALT, &FOLLOW_OR_ALT_in_oper454); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleoperEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper459);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper463);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= booleanResponse(asBoolean(e1) || asBoolean(e2), e);
        	                
        	        }

        	    }
        	    break;
        	case 9:
        	    // VerbQueryLanguageTreeParser.g:150:4: ^( (e= XOR | e= XOR_ALT ) e1= expr e2= expr )
        	    {

        	        // VerbQueryLanguageTreeParser.g:150:6: (e= XOR | e= XOR_ALT )
        	        {
        	            int alt9=2;
        	            switch ( LA(1) ) 
        	            {
        	            case XOR:
        	            	{
        	            		alt9=1;
        	            	}
        	                break;
        	            case XOR_ALT:
        	            	{
        	            		alt9=2;
        	            	}
        	                break;

        	            default:
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	                EXCEPTION->message      = (void *)"";
        	                EXCEPTION->decisionNum  = 9;
        	                EXCEPTION->state        = 0;


        	                goto ruleoperEx;
        	            }

        	            switch (alt9) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguageTreeParser.g:150:7: e= XOR
        	        	    {
        	        	        e = (pANTLR3_BASE_TREE) MATCHT(XOR, &FOLLOW_XOR_in_oper479); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleoperEx;
        	        	        }


        	        	    }
        	        	    break;
        	        	case 2:
        	        	    // VerbQueryLanguageTreeParser.g:150:15: e= XOR_ALT
        	        	    {
        	        	        e = (pANTLR3_BASE_TREE) MATCHT(XOR_ALT, &FOLLOW_XOR_ALT_in_oper485); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleoperEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper490);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper494);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= booleanResponse(asBoolean(e1) ^ asBoolean(e2), e);
        	                
        	        }

        	    }
        	    break;
        	case 10:
        	    // VerbQueryLanguageTreeParser.g:154:4: ^(e= ADD e1= expr e2= expr )
        	    {
        	        e = (pANTLR3_BASE_TREE) MATCHT(ADD, &FOLLOW_ADD_in_oper509); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper513);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper517);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= numberResponse(asNumber(e1) + asNumber(e2), e);
        	                
        	        }

        	    }
        	    break;
        	case 11:
        	    // VerbQueryLanguageTreeParser.g:158:4: ^(e= SUB e1= expr e2= expr )
        	    {
        	        e = (pANTLR3_BASE_TREE) MATCHT(SUB, &FOLLOW_SUB_in_oper532); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper536);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper540);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= numberResponse(asNumber(e1) - asNumber(e2), e);
        	                
        	        }

        	    }
        	    break;
        	case 12:
        	    // VerbQueryLanguageTreeParser.g:162:4: ^(e= MULT e1= expr e2= expr )
        	    {
        	        e = (pANTLR3_BASE_TREE) MATCHT(MULT, &FOLLOW_MULT_in_oper555); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper559);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper563);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= numberResponse(asNumber(e1) * asNumber(e2), e);
        	                
        	        }

        	    }
        	    break;
        	case 13:
        	    // VerbQueryLanguageTreeParser.g:166:4: ^(e= SLASH e1= expr e2= expr )
        	    {
        	        e = (pANTLR3_BASE_TREE) MATCHT(SLASH, &FOLLOW_SLASH_in_oper578); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper582);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper586);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= numberResponse(asNumber(e1) / asNumber(e2), e);
        	                
        	        }

        	    }
        	    break;
        	case 14:
        	    // VerbQueryLanguageTreeParser.g:170:4: ^(e= MOD e1= expr e2= expr )
        	    {
        	        e = (pANTLR3_BASE_TREE) MATCHT(MOD, &FOLLOW_MOD_in_oper601); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_DOWN, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper605);
        	        e1=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        FOLLOWPUSH(FOLLOW_expr_in_oper609);
        	        e2=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }


        	        MATCHT(ANTLR3_TOKEN_UP, NULL); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleoperEx;
        	        }

        	        {

        	                  result= numberResponse(asInt(e1) % asInt(e2), e);
        	                
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleoperEx; /* Prevent compiler warnings */
    ruleoperEx: ;

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
            }


    return result;
}
/* $ANTLR end oper */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
