/** \file
 *  This C source file was generated by $ANTLR version 3.2 Sep 23, 2009 12:02:23
 *
 *     -  From the grammar source file : VerbQueryLanguage.g
 *     -                            On : 2010-06-10 11:23:12
 *     -                for the parser : VerbQueryLanguageParserParser *
 * Editing it, at least manually, is not wise. 
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD licence"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "VerbQueryLanguageParser.h"
/* ----------------------------------------- */





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */
 
#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   pVerbQueryLanguageParser_##scope##_SCOPE
#define SCOPE_STACK(scope)  pVerbQueryLanguageParser_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->pVerbQueryLanguageParser_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->pVerbQueryLanguageParser_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))

/* Macros for accessing things in the parser
 */
 
#undef	    PARSER		    
#undef	    RECOGNIZER		    
#undef	    HAVEPARSEDRULE
#undef		MEMOIZE
#undef	    INPUT
#undef	    STRSTREAM
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    MATCHT
#undef	    MATCHANYT
#undef	    FOLLOWSTACK
#undef	    FOLLOWPUSH
#undef	    FOLLOWPOP
#undef	    PRECOVER
#undef	    PREPORTERROR
#undef	    LA
#undef	    LT
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    PERRORRECOVERY
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    RECOVERFROMMISMATCHEDSET
#undef	    RECOVERFROMMISMATCHEDELEMENT
#undef		INDEX
#undef      ADAPTOR
#undef		SEEK
#undef	    RULEMEMO		    
#undef		DBG

#define	    PARSER							ctx->pParser  
#define	    RECOGNIZER						PARSER->rec
#define		PSRSTATE						RECOGNIZER->state
#define	    HAVEPARSEDRULE(r)				RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		MEMOIZE(ri,si)					RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define	    INPUT							PARSER->tstream
#define	    STRSTREAM						INPUT
#define		ISTREAM							INPUT->istream
#define		INDEX()							ISTREAM->index(INPUT->istream)
#define	    HASEXCEPTION()					(PSRSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION						PSRSTATE->exception
#define	    MATCHT(t, fs)					RECOGNIZER->match(RECOGNIZER, t, fs)
#define	    MATCHANYT()						RECOGNIZER->matchAny(RECOGNIZER)
#define	    FOLLOWSTACK					    PSRSTATE->following
#define	    FOLLOWPUSH(x)					FOLLOWSTACK->push(FOLLOWSTACK, ((void *)(&(x))), NULL)
#define	    FOLLOWPOP()						FOLLOWSTACK->pop(FOLLOWSTACK)
#define	    PRECOVER()						RECOGNIZER->recover(RECOGNIZER)
#define	    PREPORTERROR()					RECOGNIZER->reportError(RECOGNIZER)
#define	    LA(n)							INPUT->istream->_LA(ISTREAM, n)
#define	    LT(n)							INPUT->_LT(INPUT, n)
#define	    CONSTRUCTEX()					RECOGNIZER->exConstruct(RECOGNIZER)
#define	    CONSUME()						ISTREAM->consume(ISTREAM)
#define	    MARK()							ISTREAM->mark(ISTREAM)
#define	    REWIND(m)						ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()					ISTREAM->rewindLast(ISTREAM)
#define		SEEK(n)							ISTREAM->seek(ISTREAM, n)
#define	    PERRORRECOVERY					PSRSTATE->errorRecovery
#define	    FAILEDFLAG						PSRSTATE->failed
#define	    HASFAILED()						(FAILEDFLAG == ANTLR3_TRUE)
#define	    BACKTRACKING					PSRSTATE->backtracking
#define	    RECOVERFROMMISMATCHEDSET(s)		RECOGNIZER->recoverFromMismatchedSet(RECOGNIZER, s)
#define	    RECOVERFROMMISMATCHEDELEMENT(e)	RECOGNIZER->recoverFromMismatchedElement(RECOGNIZER, s)
#define     ADAPTOR                         ctx->adaptor
#define		RULEMEMO						PSRSTATE->ruleMemo
#define		DBG								RECOGNIZER->debugger

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */



/** \brief Table of all token names in symbolic order, mainly used for
 *         error reporting.
 */
pANTLR3_UINT8   VerbQueryLanguageParserTokenNames[41+4]
     = {
        (pANTLR3_UINT8) "<invalid>",       /* String to print to indicate an invalid token */
        (pANTLR3_UINT8) "<EOR>",
        (pANTLR3_UINT8) "<DOWN>", 
        (pANTLR3_UINT8) "<UP>", 
        (pANTLR3_UINT8) "NODE_PREDICATE",
        (pANTLR3_UINT8) "NODE_PATH",
        (pANTLR3_UINT8) "SLASH",
        (pANTLR3_UINT8) "SQL",
        (pANTLR3_UINT8) "AT",
        (pANTLR3_UINT8) "EQUALITY",
        (pANTLR3_UINT8) "EQUALITY_ALT",
        (pANTLR3_UINT8) "INEQUALITY",
        (pANTLR3_UINT8) "INEQUALITY_ALT",
        (pANTLR3_UINT8) "LESS",
        (pANTLR3_UINT8) "LTE",
        (pANTLR3_UINT8) "GREATER",
        (pANTLR3_UINT8) "GTE",
        (pANTLR3_UINT8) "AND",
        (pANTLR3_UINT8) "OR",
        (pANTLR3_UINT8) "XOR",
        (pANTLR3_UINT8) "NOT",
        (pANTLR3_UINT8) "ADD",
        (pANTLR3_UINT8) "SUB",
        (pANTLR3_UINT8) "MULT",
        (pANTLR3_UINT8) "MOD",
        (pANTLR3_UINT8) "IFTRUE",
        (pANTLR3_UINT8) "IFFALSE",
        (pANTLR3_UINT8) "LBRACKET",
        (pANTLR3_UINT8) "RBRACKET",
        (pANTLR3_UINT8) "LPAREN",
        (pANTLR3_UINT8) "RPAREN",
        (pANTLR3_UINT8) "COMMA",
        (pANTLR3_UINT8) "PATH",
        (pANTLR3_UINT8) "VARIABLE",
        (pANTLR3_UINT8) "STRING",
        (pANTLR3_UINT8) "INT",
        (pANTLR3_UINT8) "FLOAT",
        (pANTLR3_UINT8) "FUNCTION",
        (pANTLR3_UINT8) "AXIS",
        (pANTLR3_UINT8) "AND_ALT",
        (pANTLR3_UINT8) "OR_ALT",
        (pANTLR3_UINT8) "XOR_ALT",
        (pANTLR3_UINT8) "ESC_SEQ",
        (pANTLR3_UINT8) "PATH_END",
        (pANTLR3_UINT8) "WS"
       };

        

// Forward declare the locally static matching functions we have generated.
//
static VerbQueryLanguageParser_start_return	start    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_sqlquery_return	sqlquery    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_expr_return	expr    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_value_expr_return	value_expr    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_value_return	value    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_function_return	function    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_path_return	path    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_predicate_return	predicate    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_predicate_expr_return	predicate_expr    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_predicate_value_expr_return	predicate_value_expr    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_predicate_oper_return	predicate_oper    (pVerbQueryLanguageParser ctx);
static VerbQueryLanguageParser_oper_return	oper    (pVerbQueryLanguageParser ctx);
static void	VerbQueryLanguageParserFree(pVerbQueryLanguageParser ctx);
/* For use in tree output where we are accumulating rule labels via label += ruleRef
 * we need a function that knows how to free a return scope when the list is destroyed. 
 * We cannot just use ANTLR3_FREE because in debug tracking mode, this is a macro.
 */
static	void ANTLR3_CDECL freeScope(void * scope)
{
    ANTLR3_FREE(scope);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "VerbQueryLanguage.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}
/** \brief Create a new VerbQueryLanguageParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pVerbQueryLanguageParser
VerbQueryLanguageParserNew   (pANTLR3_COMMON_TOKEN_STREAM instream)
{
	// See if we can create a new parser with the standard constructor
	//
	return VerbQueryLanguageParserNewSSD(instream, NULL);
}

/** \brief Create a new VerbQueryLanguageParser parser and return a context for it.
 *
 * \param[in] instream Pointer to an input stream interface.
 *
 * \return Pointer to new parser context upon success.
 */
ANTLR3_API pVerbQueryLanguageParser
VerbQueryLanguageParserNewSSD   (pANTLR3_COMMON_TOKEN_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    pVerbQueryLanguageParser ctx;	    /* Context structure we will build and return   */
    
    ctx	= (pVerbQueryLanguageParser) ANTLR3_CALLOC(1, sizeof(VerbQueryLanguageParser));
    
    if	(ctx == NULL)
    {
		// Failed to allocate memory for parser context
		//
        return  NULL;
    }
    
    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * the base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 parser function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function. 
     *
     * We don't use the macros defined in VerbQueryLanguageParser.h here, in order that you can get a sense
     * of what goes where.
     */

    /* Create a base parser/recognizer, using the supplied token stream
     */
    ctx->pParser	    = antlr3ParserNewStream(ANTLR3_SIZE_HINT, instream->tstream, state);
    /* Install the implementation of our VerbQueryLanguageParser interface
     */
    ctx->start	= start;
    ctx->sqlquery	= sqlquery;
    ctx->expr	= expr;
    ctx->value_expr	= value_expr;
    ctx->value	= value;
    ctx->function	= function;
    ctx->path	= path;
    ctx->predicate	= predicate;
    ctx->predicate_expr	= predicate_expr;
    ctx->predicate_value_expr	= predicate_value_expr;
    ctx->predicate_oper	= predicate_oper;
    ctx->oper	= oper;
    ctx->free			= VerbQueryLanguageParserFree;
    ctx->getGrammarFileName	= getGrammarFileName;
    
    /* Install the scope pushing methods.
     */
    ADAPTOR	= ANTLR3_TREE_ADAPTORNew(instream->tstream->tokenSource->strFactory);
    ctx->vectors	= antlr3VectorFactoryNew(0);
    

	
    /* Install the token table
     */
    PSRSTATE->tokenNames   = VerbQueryLanguageParserTokenNames;
    
    
    /* Return the newly built parser to the caller
     */
    return  ctx;
}

/** Free the parser resources
 */
 static void
 VerbQueryLanguageParserFree(pVerbQueryLanguageParser ctx)
 {
    /* Free any scope memory
     */
    
    ctx->vectors->close(ctx->vectors);
    /* We created the adaptor so we must free it
     */
    ADAPTOR->free(ADAPTOR);
	// Free this parser
	//
    ctx->pParser->free(ctx->pParser);
    ANTLR3_FREE(ctx);

    /* Everything is released, so we can return
     */
    return;
 }
 
/** Return token names used by this parser
 *
 * The returned pointer is used as an index into the token names table (using the token 
 * number as the index).
 * 
 * \return Pointer to first char * in the table.
 */
static pANTLR3_UINT8    *getTokenNames() 
{
        return VerbQueryLanguageParserTokenNames; 
}

    
/* Declare the bitsets
 */

/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_start293  */
static	ANTLR3_BITWORD FOLLOW_expr_in_start293_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_start293	= { FOLLOW_expr_in_start293_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_sqlquery_in_start297  */
static	ANTLR3_BITWORD FOLLOW_sqlquery_in_start297_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000000) };
static  ANTLR3_BITSET_LIST FOLLOW_sqlquery_in_start297	= { FOLLOW_sqlquery_in_start297_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_EOF_in_start300  */
static	ANTLR3_BITWORD FOLLOW_EOF_in_start300_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_EOF_in_start300	= { FOLLOW_EOF_in_start300_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_SQL_in_sqlquery312  */
static	ANTLR3_BITWORD FOLLOW_SQL_in_sqlquery312_bits[]	= { ANTLR3_UINT64_LIT(0x0000000100000000) };
static  ANTLR3_BITSET_LIST FOLLOW_SQL_in_sqlquery312	= { FOLLOW_SQL_in_sqlquery312_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PATH_in_sqlquery314  */
static	ANTLR3_BITWORD FOLLOW_PATH_in_sqlquery314_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_PATH_in_sqlquery314	= { FOLLOW_PATH_in_sqlquery314_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_NOT_in_expr335  */
static	ANTLR3_BITWORD FOLLOW_NOT_in_expr335_bits[]	= { ANTLR3_UINT64_LIT(0x0000007F20100100) };
static  ANTLR3_BITSET_LIST FOLLOW_NOT_in_expr335	= { FOLLOW_NOT_in_expr335_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_expr337  */
static	ANTLR3_BITWORD FOLLOW_expr_in_expr337_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_expr337	= { FOLLOW_expr_in_expr337_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_expr_in_expr351  */
static	ANTLR3_BITWORD FOLLOW_value_expr_in_expr351_bits[]	= { ANTLR3_UINT64_LIT(0x0000038001EFFE42) };
static  ANTLR3_BITSET_LIST FOLLOW_value_expr_in_expr351	= { FOLLOW_value_expr_in_expr351_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_oper_in_expr354  */
static	ANTLR3_BITWORD FOLLOW_oper_in_expr354_bits[]	= { ANTLR3_UINT64_LIT(0x0000007F20100100) };
static  ANTLR3_BITSET_LIST FOLLOW_oper_in_expr354	= { FOLLOW_oper_in_expr354_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_expr_in_expr357  */
static	ANTLR3_BITWORD FOLLOW_value_expr_in_expr357_bits[]	= { ANTLR3_UINT64_LIT(0x0000038001EFFE42) };
static  ANTLR3_BITSET_LIST FOLLOW_value_expr_in_expr357	= { FOLLOW_value_expr_in_expr357_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LPAREN_in_value_expr371  */
static	ANTLR3_BITWORD FOLLOW_LPAREN_in_value_expr371_bits[]	= { ANTLR3_UINT64_LIT(0x0000007F20100100) };
static  ANTLR3_BITSET_LIST FOLLOW_LPAREN_in_value_expr371	= { FOLLOW_LPAREN_in_value_expr371_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_value_expr373  */
static	ANTLR3_BITWORD FOLLOW_expr_in_value_expr373_bits[]	= { ANTLR3_UINT64_LIT(0x0000000040000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_value_expr373	= { FOLLOW_expr_in_value_expr373_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAREN_in_value_expr375  */
static	ANTLR3_BITWORD FOLLOW_RPAREN_in_value_expr375_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAREN_in_value_expr375	= { FOLLOW_RPAREN_in_value_expr375_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_value_expr388  */
static	ANTLR3_BITWORD FOLLOW_value_in_value_expr388_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_value_expr388	= { FOLLOW_value_in_value_expr388_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_function_in_value_expr392  */
static	ANTLR3_BITWORD FOLLOW_function_in_value_expr392_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_function_in_value_expr392	= { FOLLOW_function_in_value_expr392_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_in_value_expr396  */
static	ANTLR3_BITWORD FOLLOW_path_in_value_expr396_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_in_value_expr396	= { FOLLOW_path_in_value_expr396_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_value0  */
static	ANTLR3_BITWORD FOLLOW_set_in_value0_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_value0	= { FOLLOW_set_in_value0_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_FUNCTION_in_function431  */
static	ANTLR3_BITWORD FOLLOW_FUNCTION_in_function431_bits[]	= { ANTLR3_UINT64_LIT(0x0000007FE0100100) };
static  ANTLR3_BITSET_LIST FOLLOW_FUNCTION_in_function431	= { FOLLOW_FUNCTION_in_function431_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_function433  */
static	ANTLR3_BITWORD FOLLOW_expr_in_function433_bits[]	= { ANTLR3_UINT64_LIT(0x00000000C0000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_function433	= { FOLLOW_expr_in_function433_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_COMMA_in_function437  */
static	ANTLR3_BITWORD FOLLOW_COMMA_in_function437_bits[]	= { ANTLR3_UINT64_LIT(0x0000007F20100100) };
static  ANTLR3_BITSET_LIST FOLLOW_COMMA_in_function437	= { FOLLOW_COMMA_in_function437_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_expr_in_function439  */
static	ANTLR3_BITWORD FOLLOW_expr_in_function439_bits[]	= { ANTLR3_UINT64_LIT(0x00000000C0000000) };
static  ANTLR3_BITSET_LIST FOLLOW_expr_in_function439	= { FOLLOW_expr_in_function439_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RPAREN_in_function443  */
static	ANTLR3_BITWORD FOLLOW_RPAREN_in_function443_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RPAREN_in_function443	= { FOLLOW_RPAREN_in_function443_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_PATH_in_path473  */
static	ANTLR3_BITWORD FOLLOW_PATH_in_path473_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000002) };
static  ANTLR3_BITSET_LIST FOLLOW_PATH_in_path473	= { FOLLOW_PATH_in_path473_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AXIS_in_path479  */
static	ANTLR3_BITWORD FOLLOW_AXIS_in_path479_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000002) };
static  ANTLR3_BITSET_LIST FOLLOW_AXIS_in_path479	= { FOLLOW_AXIS_in_path479_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_in_path482  */
static	ANTLR3_BITWORD FOLLOW_predicate_in_path482_bits[]	= { ANTLR3_UINT64_LIT(0x0000000008000002) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_in_path482	= { FOLLOW_predicate_in_path482_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_AT_in_path500  */
static	ANTLR3_BITWORD FOLLOW_AT_in_path500_bits[]	= { ANTLR3_UINT64_LIT(0x0000007F20100100) };
static  ANTLR3_BITSET_LIST FOLLOW_AT_in_path500	= { FOLLOW_AT_in_path500_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_in_path502  */
static	ANTLR3_BITWORD FOLLOW_path_in_path502_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_in_path502	= { FOLLOW_path_in_path502_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_LBRACKET_in_predicate521  */
static	ANTLR3_BITWORD FOLLOW_LBRACKET_in_predicate521_bits[]	= { ANTLR3_UINT64_LIT(0x0000007F20100100) };
static  ANTLR3_BITSET_LIST FOLLOW_LBRACKET_in_predicate521	= { FOLLOW_LBRACKET_in_predicate521_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_expr_in_predicate523  */
static	ANTLR3_BITWORD FOLLOW_predicate_expr_in_predicate523_bits[]	= { ANTLR3_UINT64_LIT(0x0000000010000000) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_expr_in_predicate523	= { FOLLOW_predicate_expr_in_predicate523_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_RBRACKET_in_predicate525  */
static	ANTLR3_BITWORD FOLLOW_RBRACKET_in_predicate525_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_RBRACKET_in_predicate525	= { FOLLOW_RBRACKET_in_predicate525_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_INT_in_predicate_expr546  */
static	ANTLR3_BITWORD FOLLOW_INT_in_predicate_expr546_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_INT_in_predicate_expr546	= { FOLLOW_INT_in_predicate_expr546_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_value_expr_in_predicate_expr551  */
static	ANTLR3_BITWORD FOLLOW_predicate_value_expr_in_predicate_expr551_bits[]	= { ANTLR3_UINT64_LIT(0x000001800007FE00) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_value_expr_in_predicate_expr551	= { FOLLOW_predicate_value_expr_in_predicate_expr551_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_oper_in_predicate_expr553  */
static	ANTLR3_BITWORD FOLLOW_predicate_oper_in_predicate_expr553_bits[]	= { ANTLR3_UINT64_LIT(0x0000007F20100100) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_oper_in_predicate_expr553	= { FOLLOW_predicate_oper_in_predicate_expr553_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_predicate_value_expr_in_predicate_expr555  */
static	ANTLR3_BITWORD FOLLOW_predicate_value_expr_in_predicate_expr555_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_predicate_value_expr_in_predicate_expr555	= { FOLLOW_predicate_value_expr_in_predicate_expr555_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_value_in_predicate_value_expr568  */
static	ANTLR3_BITWORD FOLLOW_value_in_predicate_value_expr568_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_value_in_predicate_value_expr568	= { FOLLOW_value_in_predicate_value_expr568_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_function_in_predicate_value_expr572  */
static	ANTLR3_BITWORD FOLLOW_function_in_predicate_value_expr572_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_function_in_predicate_value_expr572	= { FOLLOW_function_in_predicate_value_expr572_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_path_in_predicate_value_expr576  */
static	ANTLR3_BITWORD FOLLOW_path_in_predicate_value_expr576_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_path_in_predicate_value_expr576	= { FOLLOW_path_in_predicate_value_expr576_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_predicate_oper0  */
static	ANTLR3_BITWORD FOLLOW_set_in_predicate_oper0_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_predicate_oper0	= { FOLLOW_set_in_predicate_oper0_bits, 1	};
/** Bitset defining follow set for error recovery in rule state: FOLLOW_set_in_oper0  */
static	ANTLR3_BITWORD FOLLOW_set_in_oper0_bits[]	= { ANTLR3_UINT64_LIT(0x0000000000000002) };
static  ANTLR3_BITSET_LIST FOLLOW_set_in_oper0	= { FOLLOW_set_in_oper0_bits, 1	};
     

 
 
/* ==============================================
 * Parsing rules
 */
/** 
 * $ANTLR start start
 * VerbQueryLanguage.g:47:1: start : ( expr | sqlquery ) EOF ;
 */
static VerbQueryLanguageParser_start_return
start(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_start_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    EOF3;
    VerbQueryLanguageParser_expr_return expr1;
    #undef	RETURN_TYPE_expr1
    #define	RETURN_TYPE_expr1 VerbQueryLanguageParser_expr_return

    VerbQueryLanguageParser_sqlquery_return sqlquery2;
    #undef	RETURN_TYPE_sqlquery2
    #define	RETURN_TYPE_sqlquery2 VerbQueryLanguageParser_sqlquery_return

    pANTLR3_BASE_TREE EOF3_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    EOF3       = NULL;
    expr1.tree = NULL;

    sqlquery2.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    EOF3_tree   = NULL;


    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:48:2: ( ( expr | sqlquery ) EOF )
        // VerbQueryLanguage.g:48:4: ( expr | sqlquery ) EOF
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // VerbQueryLanguage.g:48:4: ( expr | sqlquery )
            {
                int alt1=2;
                switch ( LA(1) ) 
                {
                case AT:
                case NOT:
                case LPAREN:
                case PATH:
                case VARIABLE:
                case STRING:
                case INT:
                case FLOAT:
                case FUNCTION:
                case AXIS:
                	{
                		alt1=1;
                	}
                    break;
                case SQL:
                	{
                		alt1=2;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 1;
                    EXCEPTION->state        = 0;


                    goto rulestartEx;
                }

                switch (alt1) 
                {
            	case 1:
            	    // VerbQueryLanguage.g:48:5: expr
            	    {
            	        FOLLOWPUSH(FOLLOW_expr_in_start293);
            	        expr1=expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulestartEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, expr1.tree);

            	    }
            	    break;
            	case 2:
            	    // VerbQueryLanguage.g:48:12: sqlquery
            	    {
            	        FOLLOWPUSH(FOLLOW_sqlquery_in_start297);
            	        sqlquery2=sqlquery(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulestartEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, sqlquery2.tree);

            	    }
            	    break;

                }
            }
            EOF3 = (pANTLR3_COMMON_TOKEN) MATCHT(EOF, &FOLLOW_EOF_in_start300); 
            if  (HASEXCEPTION())
            {
                goto rulestartEx;
            }

            EOF3_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, EOF3));
            ADAPTOR->addChild(ADAPTOR, root_0, EOF3_tree);


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulestartEx; /* Prevent compiler warnings */
    rulestartEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end start */

/** 
 * $ANTLR start sqlquery
 * VerbQueryLanguage.g:51:1: sqlquery : SQL PATH -> ^( NODE_PATH SQL PATH ) ;
 */
static VerbQueryLanguageParser_sqlquery_return
sqlquery(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_sqlquery_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    SQL4;
    pANTLR3_COMMON_TOKEN    PATH5;

    pANTLR3_BASE_TREE SQL4_tree;
    pANTLR3_BASE_TREE PATH5_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_SQL;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_PATH;

    /* Initialize rule variables
     */


    root_0 = NULL;

    SQL4       = NULL;
    PATH5       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    SQL4_tree   = NULL;
    PATH5_tree   = NULL;

    stream_SQL   = NULL;
    #define CREATE_stream_SQL  if (stream_SQL == NULL) {stream_SQL = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token SQL"); } 
    stream_PATH   = NULL;
    #define CREATE_stream_PATH  if (stream_PATH == NULL) {stream_PATH = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token PATH"); } 

    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:52:2: ( SQL PATH -> ^( NODE_PATH SQL PATH ) )
        // VerbQueryLanguage.g:52:4: SQL PATH
        {
            SQL4 = (pANTLR3_COMMON_TOKEN) MATCHT(SQL, &FOLLOW_SQL_in_sqlquery312); 
            if  (HASEXCEPTION())
            {
                goto rulesqlqueryEx;
            }
             
            CREATE_stream_SQL; stream_SQL->add(stream_SQL, SQL4, NULL);

            PATH5 = (pANTLR3_COMMON_TOKEN) MATCHT(PATH, &FOLLOW_PATH_in_sqlquery314); 
            if  (HASEXCEPTION())
            {
                goto rulesqlqueryEx;
            }
             
            CREATE_stream_PATH; stream_PATH->add(stream_PATH, PATH5, NULL);


             
            /* AST REWRITE
             * elements          : SQL, PATH
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 52:13: -> ^( NODE_PATH SQL PATH )
            	{
            	    // VerbQueryLanguage.g:52:16: ^( NODE_PATH SQL PATH )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, NODE_PATH, (pANTLR3_UINT8)"NODE_PATH"), root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_SQL == NULL ? NULL : stream_SQL->nextNode(stream_SQL));
            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_PATH == NULL ? NULL : stream_PATH->nextNode(stream_PATH));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}

            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulesqlqueryEx; /* Prevent compiler warnings */
    rulesqlqueryEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_SQL != NULL) stream_SQL->free(stream_SQL);
        if (stream_PATH != NULL) stream_PATH->free(stream_PATH);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end sqlquery */

/** 
 * $ANTLR start expr
 * VerbQueryLanguage.g:55:1: expr : ( NOT expr -> ^( NOT expr ) | value_expr ( oper value_expr )* );
 */
static VerbQueryLanguageParser_expr_return
expr(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_expr_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    NOT6;
    VerbQueryLanguageParser_expr_return expr7;
    #undef	RETURN_TYPE_expr7
    #define	RETURN_TYPE_expr7 VerbQueryLanguageParser_expr_return

    VerbQueryLanguageParser_value_expr_return value_expr8;
    #undef	RETURN_TYPE_value_expr8
    #define	RETURN_TYPE_value_expr8 VerbQueryLanguageParser_value_expr_return

    VerbQueryLanguageParser_oper_return oper9;
    #undef	RETURN_TYPE_oper9
    #define	RETURN_TYPE_oper9 VerbQueryLanguageParser_oper_return

    VerbQueryLanguageParser_value_expr_return value_expr10;
    #undef	RETURN_TYPE_value_expr10
    #define	RETURN_TYPE_value_expr10 VerbQueryLanguageParser_value_expr_return

    pANTLR3_BASE_TREE NOT6_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_NOT;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */


    root_0 = NULL;

    NOT6       = NULL;
    expr7.tree = NULL;

    value_expr8.tree = NULL;

    oper9.tree = NULL;

    value_expr10.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    NOT6_tree   = NULL;

    stream_NOT   = NULL;
    #define CREATE_stream_NOT  if (stream_NOT == NULL) {stream_NOT = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token NOT"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;
    {
        {
            //  VerbQueryLanguage.g:56:2: ( NOT expr -> ^( NOT expr ) | value_expr ( oper value_expr )* )
            
            ANTLR3_UINT32 alt3;

            alt3=2;

            switch ( LA(1) ) 
            {
            case NOT:
            	{
            		alt3=1;
            	}
                break;
            case AT:
            case LPAREN:
            case PATH:
            case VARIABLE:
            case STRING:
            case INT:
            case FLOAT:
            case FUNCTION:
            case AXIS:
            	{
            		alt3=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 3;
                EXCEPTION->state        = 0;


                goto ruleexprEx;
            }

            switch (alt3) 
            {
        	case 1:
        	    // VerbQueryLanguage.g:56:4: NOT expr
        	    {
        	        NOT6 = (pANTLR3_COMMON_TOKEN) MATCHT(NOT, &FOLLOW_NOT_in_expr335); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }
        	         
        	        CREATE_stream_NOT; stream_NOT->add(stream_NOT, NOT6, NULL);

        	        FOLLOWPUSH(FOLLOW_expr_in_expr337);
        	        expr7=expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        CREATE_stream_expr; stream_expr->add(stream_expr, expr7.tree, NULL);

        	         
        	        /* AST REWRITE
        	         * elements          : NOT, expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 56:13: -> ^( NOT expr )
        	        	{
        	        	    // VerbQueryLanguage.g:56:16: ^( NOT expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_NOT == NULL ? NULL : stream_NOT->nextNode(stream_NOT), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguage.g:57:4: value_expr ( oper value_expr )*
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_value_expr_in_expr351);
        	        value_expr8=value_expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleexprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, value_expr8.tree);

        	        // VerbQueryLanguage.g:57:15: ( oper value_expr )*

        	        for (;;)
        	        {
        	            int alt2=2;
        	            switch ( LA(1) ) 
        	            {
        	            case SLASH:
        	            case EQUALITY:
        	            case EQUALITY_ALT:
        	            case INEQUALITY:
        	            case INEQUALITY_ALT:
        	            case LESS:
        	            case LTE:
        	            case GREATER:
        	            case GTE:
        	            case AND:
        	            case OR:
        	            case XOR:
        	            case ADD:
        	            case SUB:
        	            case MULT:
        	            case MOD:
        	            case AND_ALT:
        	            case OR_ALT:
        	            case XOR_ALT:
        	            	{
        	            		alt2=1;
        	            	}
        	                break;

        	            }

        	            switch (alt2) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguage.g:57:16: oper value_expr
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_oper_in_expr354);
        	        	        oper9=oper(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleexprEx;
        	        	        }

        	        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, oper9.tree, root_0));
        	        	        FOLLOWPUSH(FOLLOW_value_expr_in_expr357);
        	        	        value_expr10=value_expr(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleexprEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, value_expr10.tree);

        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop2;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop2: ; /* Jump out to here if this rule does not match */


        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto ruleexprEx; /* Prevent compiler warnings */
    ruleexprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_NOT != NULL) stream_NOT->free(stream_NOT);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end expr */

/** 
 * $ANTLR start value_expr
 * VerbQueryLanguage.g:60:1: value_expr : ( ( LPAREN expr RPAREN ) -> ^( expr ) | ( value | function | path ) );
 */
static VerbQueryLanguageParser_value_expr_return
value_expr(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_value_expr_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    LPAREN11;
    pANTLR3_COMMON_TOKEN    RPAREN13;
    VerbQueryLanguageParser_expr_return expr12;
    #undef	RETURN_TYPE_expr12
    #define	RETURN_TYPE_expr12 VerbQueryLanguageParser_expr_return

    VerbQueryLanguageParser_value_return value14;
    #undef	RETURN_TYPE_value14
    #define	RETURN_TYPE_value14 VerbQueryLanguageParser_value_return

    VerbQueryLanguageParser_function_return function15;
    #undef	RETURN_TYPE_function15
    #define	RETURN_TYPE_function15 VerbQueryLanguageParser_function_return

    VerbQueryLanguageParser_path_return path16;
    #undef	RETURN_TYPE_path16
    #define	RETURN_TYPE_path16 VerbQueryLanguageParser_path_return

    pANTLR3_BASE_TREE LPAREN11_tree;
    pANTLR3_BASE_TREE RPAREN13_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_RPAREN;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_LPAREN;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */


    root_0 = NULL;

    LPAREN11       = NULL;
    RPAREN13       = NULL;
    expr12.tree = NULL;

    value14.tree = NULL;

    function15.tree = NULL;

    path16.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    LPAREN11_tree   = NULL;
    RPAREN13_tree   = NULL;

    stream_RPAREN   = NULL;
    #define CREATE_stream_RPAREN  if (stream_RPAREN == NULL) {stream_RPAREN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token RPAREN"); } 
    stream_LPAREN   = NULL;
    #define CREATE_stream_LPAREN  if (stream_LPAREN == NULL) {stream_LPAREN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token LPAREN"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;
    {
        {
            //  VerbQueryLanguage.g:61:2: ( ( LPAREN expr RPAREN ) -> ^( expr ) | ( value | function | path ) )
            
            ANTLR3_UINT32 alt5;

            alt5=2;

            switch ( LA(1) ) 
            {
            case LPAREN:
            	{
            		alt5=1;
            	}
                break;
            case AT:
            case PATH:
            case VARIABLE:
            case STRING:
            case INT:
            case FLOAT:
            case FUNCTION:
            case AXIS:
            	{
            		alt5=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 5;
                EXCEPTION->state        = 0;


                goto rulevalue_exprEx;
            }

            switch (alt5) 
            {
        	case 1:
        	    // VerbQueryLanguage.g:61:4: ( LPAREN expr RPAREN )
        	    {
        	        // VerbQueryLanguage.g:61:4: ( LPAREN expr RPAREN )
        	        // VerbQueryLanguage.g:61:5: LPAREN expr RPAREN
        	        {
        	            LPAREN11 = (pANTLR3_COMMON_TOKEN) MATCHT(LPAREN, &FOLLOW_LPAREN_in_value_expr371); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto rulevalue_exprEx;
        	            }
        	             
        	            CREATE_stream_LPAREN; stream_LPAREN->add(stream_LPAREN, LPAREN11, NULL);

        	            FOLLOWPUSH(FOLLOW_expr_in_value_expr373);
        	            expr12=expr(ctx);

        	            FOLLOWPOP();
        	            if  (HASEXCEPTION())
        	            {
        	                goto rulevalue_exprEx;
        	            }

        	            CREATE_stream_expr; stream_expr->add(stream_expr, expr12.tree, NULL);
        	            RPAREN13 = (pANTLR3_COMMON_TOKEN) MATCHT(RPAREN, &FOLLOW_RPAREN_in_value_expr375); 
        	            if  (HASEXCEPTION())
        	            {
        	                goto rulevalue_exprEx;
        	            }
        	             
        	            CREATE_stream_RPAREN; stream_RPAREN->add(stream_RPAREN, RPAREN13, NULL);


        	        }


        	         
        	        /* AST REWRITE
        	         * elements          : expr
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 61:25: -> ^( expr )
        	        	{
        	        	    // VerbQueryLanguage.g:61:28: ^( expr )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_expr == NULL ? NULL : stream_expr->nextNode(stream_expr), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguage.g:62:4: ( value | function | path )
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


        	        // VerbQueryLanguage.g:62:4: ( value | function | path )
        	        {
        	            int alt4=3;
        	            switch ( LA(1) ) 
        	            {
        	            case VARIABLE:
        	            case STRING:
        	            case INT:
        	            case FLOAT:
        	            	{
        	            		alt4=1;
        	            	}
        	                break;
        	            case FUNCTION:
        	            	{
        	            		alt4=2;
        	            	}
        	                break;
        	            case AT:
        	            case PATH:
        	            case AXIS:
        	            	{
        	            		alt4=3;
        	            	}
        	                break;

        	            default:
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	                EXCEPTION->message      = (void *)"";
        	                EXCEPTION->decisionNum  = 4;
        	                EXCEPTION->state        = 0;


        	                goto rulevalue_exprEx;
        	            }

        	            switch (alt4) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguage.g:62:5: value
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_value_in_value_expr388);
        	        	        value14=value(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulevalue_exprEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, value14.tree);

        	        	    }
        	        	    break;
        	        	case 2:
        	        	    // VerbQueryLanguage.g:62:13: function
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_function_in_value_expr392);
        	        	        function15=function(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulevalue_exprEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, function15.tree);

        	        	    }
        	        	    break;
        	        	case 3:
        	        	    // VerbQueryLanguage.g:62:24: path
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_path_in_value_expr396);
        	        	        path16=path(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulevalue_exprEx;
        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, path16.tree);

        	        	    }
        	        	    break;

        	            }
        	        }

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulevalue_exprEx; /* Prevent compiler warnings */
    rulevalue_exprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_RPAREN != NULL) stream_RPAREN->free(stream_RPAREN);
        if (stream_LPAREN != NULL) stream_LPAREN->free(stream_LPAREN);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end value_expr */

/** 
 * $ANTLR start value
 * VerbQueryLanguage.g:65:1: value : ( VARIABLE | STRING | INT | FLOAT );
 */
static VerbQueryLanguageParser_value_return
value(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_value_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set17;

    pANTLR3_BASE_TREE set17_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    set17       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    set17_tree   = NULL;


    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:66:2: ( VARIABLE | STRING | INT | FLOAT )
        // VerbQueryLanguage.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            set17=(pANTLR3_COMMON_TOKEN)LT(1);
            if ( ((LA(1) >= VARIABLE) && (LA(1) <= FLOAT)) )
            {
                CONSUME();
                ADAPTOR->addChild(ADAPTOR, root_0, (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set17)));
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else 
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = &FOLLOW_set_in_value0;
                RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_value0);    goto rulevalueEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulevalueEx; /* Prevent compiler warnings */
    rulevalueEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end value */

/** 
 * $ANTLR start function
 * VerbQueryLanguage.g:69:1: function : FUNCTION ( expr )? ( COMMA expr )* RPAREN -> ^( FUNCTION expr ( COMMA expr )* ) ;
 */
static VerbQueryLanguageParser_function_return
function(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_function_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    FUNCTION18;
    pANTLR3_COMMON_TOKEN    COMMA20;
    pANTLR3_COMMON_TOKEN    RPAREN22;
    VerbQueryLanguageParser_expr_return expr19;
    #undef	RETURN_TYPE_expr19
    #define	RETURN_TYPE_expr19 VerbQueryLanguageParser_expr_return

    VerbQueryLanguageParser_expr_return expr21;
    #undef	RETURN_TYPE_expr21
    #define	RETURN_TYPE_expr21 VerbQueryLanguageParser_expr_return

    pANTLR3_BASE_TREE FUNCTION18_tree;
    pANTLR3_BASE_TREE COMMA20_tree;
    pANTLR3_BASE_TREE RPAREN22_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_FUNCTION;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_RPAREN;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_COMMA;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_expr;
    /* Initialize rule variables
     */


    root_0 = NULL;

    FUNCTION18       = NULL;
    COMMA20       = NULL;
    RPAREN22       = NULL;
    expr19.tree = NULL;

    expr21.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    FUNCTION18_tree   = NULL;
    COMMA20_tree   = NULL;
    RPAREN22_tree   = NULL;

    stream_FUNCTION   = NULL;
    #define CREATE_stream_FUNCTION  if (stream_FUNCTION == NULL) {stream_FUNCTION = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token FUNCTION"); } 
    stream_RPAREN   = NULL;
    #define CREATE_stream_RPAREN  if (stream_RPAREN == NULL) {stream_RPAREN = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token RPAREN"); } 
    stream_COMMA   = NULL;
    #define CREATE_stream_COMMA  if (stream_COMMA == NULL) {stream_COMMA = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token COMMA"); } 
    stream_expr   = NULL;
    #define CREATE_stream_expr  if (stream_expr == NULL) {stream_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule expr"); }

    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:70:2: ( FUNCTION ( expr )? ( COMMA expr )* RPAREN -> ^( FUNCTION expr ( COMMA expr )* ) )
        // VerbQueryLanguage.g:70:4: FUNCTION ( expr )? ( COMMA expr )* RPAREN
        {
            FUNCTION18 = (pANTLR3_COMMON_TOKEN) MATCHT(FUNCTION, &FOLLOW_FUNCTION_in_function431); 
            if  (HASEXCEPTION())
            {
                goto rulefunctionEx;
            }
             
            CREATE_stream_FUNCTION; stream_FUNCTION->add(stream_FUNCTION, FUNCTION18, NULL);


            // VerbQueryLanguage.g:70:13: ( expr )?
            {
                int alt6=2;
                switch ( LA(1) ) 
                {
                    case AT:
                    case NOT:
                    case LPAREN:
                    case PATH:
                    case VARIABLE:
                    case STRING:
                    case INT:
                    case FLOAT:
                    case FUNCTION:
                    case AXIS:
                    	{
                    		alt6=1;
                    	}
                        break;
                }

                switch (alt6) 
                {
            	case 1:
            	    // VerbQueryLanguage.g:70:13: expr
            	    {
            	        FOLLOWPUSH(FOLLOW_expr_in_function433);
            	        expr19=expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunctionEx;
            	        }

            	        CREATE_stream_expr; stream_expr->add(stream_expr, expr19.tree, NULL);

            	    }
            	    break;

                }
            }

            // VerbQueryLanguage.g:70:19: ( COMMA expr )*

            for (;;)
            {
                int alt7=2;
                switch ( LA(1) ) 
                {
                case COMMA:
                	{
                		alt7=1;
                	}
                    break;

                }

                switch (alt7) 
                {
            	case 1:
            	    // VerbQueryLanguage.g:70:20: COMMA expr
            	    {
            	        COMMA20 = (pANTLR3_COMMON_TOKEN) MATCHT(COMMA, &FOLLOW_COMMA_in_function437); 
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunctionEx;
            	        }
            	         
            	        CREATE_stream_COMMA; stream_COMMA->add(stream_COMMA, COMMA20, NULL);

            	        FOLLOWPUSH(FOLLOW_expr_in_function439);
            	        expr21=expr(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulefunctionEx;
            	        }

            	        CREATE_stream_expr; stream_expr->add(stream_expr, expr21.tree, NULL);

            	    }
            	    break;

            	default:
            	    goto loop7;	/* break out of the loop */
            	    break;
                }
            }
            loop7: ; /* Jump out to here if this rule does not match */

            RPAREN22 = (pANTLR3_COMMON_TOKEN) MATCHT(RPAREN, &FOLLOW_RPAREN_in_function443); 
            if  (HASEXCEPTION())
            {
                goto rulefunctionEx;
            }
             
            CREATE_stream_RPAREN; stream_RPAREN->add(stream_RPAREN, RPAREN22, NULL);


             
            /* AST REWRITE
             * elements          : expr, expr, COMMA, FUNCTION
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 70:40: -> ^( FUNCTION expr ( COMMA expr )* )
            	{
            	    // VerbQueryLanguage.g:70:43: ^( FUNCTION expr ( COMMA expr )* )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_FUNCTION == NULL ? NULL : stream_FUNCTION->nextNode(stream_FUNCTION), root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));
            	        // VerbQueryLanguage.g:70:59: ( COMMA expr )*
            	        {
            	        	while ( (stream_expr != NULL && stream_expr->hasNext(stream_expr)) || (stream_COMMA != NULL && stream_COMMA->hasNext(stream_COMMA))  )
            	        	{
            	        		ADAPTOR->addChild(ADAPTOR, root_1, stream_COMMA == NULL ? NULL : stream_COMMA->nextNode(stream_COMMA));
            	        		ADAPTOR->addChild(ADAPTOR, root_1, stream_expr == NULL ? NULL : stream_expr->nextTree(stream_expr));

            	        	}
            	        	if (stream_expr != NULL) stream_expr->reset(stream_expr);
            	        	if (stream_COMMA != NULL) stream_COMMA->reset(stream_COMMA);

            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}

            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulefunctionEx; /* Prevent compiler warnings */
    rulefunctionEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_FUNCTION != NULL) stream_FUNCTION->free(stream_FUNCTION);
        if (stream_RPAREN != NULL) stream_RPAREN->free(stream_RPAREN);
        if (stream_COMMA != NULL) stream_COMMA->free(stream_COMMA);
        if (stream_expr != NULL) stream_expr->free(stream_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end function */

/** 
 * $ANTLR start path
 * VerbQueryLanguage.g:73:1: path : ( (v= PATH | v= AXIS ) ( predicate )* -> ^( NODE_PATH $v ( predicate )* ) | AT path -> ^( AT path ) );
 */
static VerbQueryLanguageParser_path_return
path(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_path_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    v;
    pANTLR3_COMMON_TOKEN    AT24;
    VerbQueryLanguageParser_predicate_return predicate23;
    #undef	RETURN_TYPE_predicate23
    #define	RETURN_TYPE_predicate23 VerbQueryLanguageParser_predicate_return

    VerbQueryLanguageParser_path_return path25;
    #undef	RETURN_TYPE_path25
    #define	RETURN_TYPE_path25 VerbQueryLanguageParser_path_return

    pANTLR3_BASE_TREE v_tree;
    pANTLR3_BASE_TREE AT24_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_AT;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_AXIS;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_PATH;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_predicate;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_path;
    /* Initialize rule variables
     */


    root_0 = NULL;

    v       = NULL;
    AT24       = NULL;
    predicate23.tree = NULL;

    path25.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    v_tree   = NULL;
    AT24_tree   = NULL;

    stream_AT   = NULL;
    #define CREATE_stream_AT  if (stream_AT == NULL) {stream_AT = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token AT"); } 
    stream_AXIS   = NULL;
    #define CREATE_stream_AXIS  if (stream_AXIS == NULL) {stream_AXIS = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token AXIS"); } 
    stream_PATH   = NULL;
    #define CREATE_stream_PATH  if (stream_PATH == NULL) {stream_PATH = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token PATH"); } 
    stream_predicate   = NULL;
    #define CREATE_stream_predicate  if (stream_predicate == NULL) {stream_predicate = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule predicate"); }
    stream_path   = NULL;
    #define CREATE_stream_path  if (stream_path == NULL) {stream_path = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule path"); }

    retval.tree  = NULL;
    {
        {
            //  VerbQueryLanguage.g:74:2: ( (v= PATH | v= AXIS ) ( predicate )* -> ^( NODE_PATH $v ( predicate )* ) | AT path -> ^( AT path ) )
            
            ANTLR3_UINT32 alt10;

            alt10=2;

            switch ( LA(1) ) 
            {
            case PATH:
            case AXIS:
            	{
            		alt10=1;
            	}
                break;
            case AT:
            	{
            		alt10=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 10;
                EXCEPTION->state        = 0;


                goto rulepathEx;
            }

            switch (alt10) 
            {
        	case 1:
        	    // VerbQueryLanguage.g:74:4: (v= PATH | v= AXIS ) ( predicate )*
        	    {

        	        // VerbQueryLanguage.g:74:4: (v= PATH | v= AXIS )
        	        {
        	            int alt8=2;
        	            switch ( LA(1) ) 
        	            {
        	            case PATH:
        	            	{
        	            		alt8=1;
        	            	}
        	                break;
        	            case AXIS:
        	            	{
        	            		alt8=2;
        	            	}
        	                break;

        	            default:
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
        	                EXCEPTION->message      = (void *)"";
        	                EXCEPTION->decisionNum  = 8;
        	                EXCEPTION->state        = 0;


        	                goto rulepathEx;
        	            }

        	            switch (alt8) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguage.g:74:5: v= PATH
        	        	    {
        	        	        v = (pANTLR3_COMMON_TOKEN) MATCHT(PATH, &FOLLOW_PATH_in_path473); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulepathEx;
        	        	        }
        	        	         
        	        	        CREATE_stream_PATH; stream_PATH->add(stream_PATH, v, NULL);


        	        	    }
        	        	    break;
        	        	case 2:
        	        	    // VerbQueryLanguage.g:74:14: v= AXIS
        	        	    {
        	        	        v = (pANTLR3_COMMON_TOKEN) MATCHT(AXIS, &FOLLOW_AXIS_in_path479); 
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulepathEx;
        	        	        }
        	        	         
        	        	        CREATE_stream_AXIS; stream_AXIS->add(stream_AXIS, v, NULL);


        	        	    }
        	        	    break;

        	            }
        	        }

        	        // VerbQueryLanguage.g:74:22: ( predicate )*

        	        for (;;)
        	        {
        	            int alt9=2;
        	            switch ( LA(1) ) 
        	            {
        	            case LBRACKET:
        	            	{
        	            		alt9=1;
        	            	}
        	                break;

        	            }

        	            switch (alt9) 
        	            {
        	        	case 1:
        	        	    // VerbQueryLanguage.g:74:22: predicate
        	        	    {
        	        	        FOLLOWPUSH(FOLLOW_predicate_in_path482);
        	        	        predicate23=predicate(ctx);

        	        	        FOLLOWPOP();
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto rulepathEx;
        	        	        }

        	        	        CREATE_stream_predicate; stream_predicate->add(stream_predicate, predicate23.tree, NULL);

        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop9;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop9: ; /* Jump out to here if this rule does not match */


        	         
        	        /* AST REWRITE
        	         * elements          : v, predicate
        	         * token labels      : v
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_v;
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_v=antlr3RewriteRuleTOKENStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token v", v);
        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 74:33: -> ^( NODE_PATH $v ( predicate )* )
        	        	{
        	        	    // VerbQueryLanguage.g:74:36: ^( NODE_PATH $v ( predicate )* )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, NODE_PATH, (pANTLR3_UINT8)"NODE_PATH"), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_v == NULL ? NULL : stream_v->nextNode(stream_v));
        	        	        // VerbQueryLanguage.g:74:51: ( predicate )*
        	        	        {
        	        	        	while ( (stream_predicate != NULL && stream_predicate->hasNext(stream_predicate))  )
        	        	        	{
        	        	        		ADAPTOR->addChild(ADAPTOR, root_1, stream_predicate == NULL ? NULL : stream_predicate->nextTree(stream_predicate));

        	        	        	}
        	        	        	if (stream_predicate != NULL) stream_predicate->reset(stream_predicate);

        	        	        }

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_v != NULL) stream_v->free(stream_v); 
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguage.g:75:4: AT path
        	    {
        	        AT24 = (pANTLR3_COMMON_TOKEN) MATCHT(AT, &FOLLOW_AT_in_path500); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepathEx;
        	        }
        	         
        	        CREATE_stream_AT; stream_AT->add(stream_AT, AT24, NULL);

        	        FOLLOWPUSH(FOLLOW_path_in_path502);
        	        path25=path(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepathEx;
        	        }

        	        CREATE_stream_path; stream_path->add(stream_path, path25.tree, NULL);

        	         
        	        /* AST REWRITE
        	         * elements          : AT, path
        	         * token labels      : 
        	         * rule labels       : retval
        	         * token list labels : 
        	         * rule list labels  : 
        	         */
        	        {
        	        	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

        	        	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

        	        	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	retval.tree    = root_0;
        	        	// 75:12: -> ^( AT path )
        	        	{
        	        	    // VerbQueryLanguage.g:75:15: ^( AT path )
        	        	    {
        	        	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
        	        	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, stream_AT == NULL ? NULL : stream_AT->nextNode(stream_AT), root_1));

        	        	        ADAPTOR->addChild(ADAPTOR, root_1, stream_path == NULL ? NULL : stream_path->nextTree(stream_path));

        	        	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
        	        	    }

        	        	}

        	        	retval.tree = root_0; // set result root
        	        	if (stream_retval != NULL) stream_retval->free(stream_retval);


        	        }
        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulepathEx; /* Prevent compiler warnings */
    rulepathEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_AT != NULL) stream_AT->free(stream_AT);
        if (stream_AXIS != NULL) stream_AXIS->free(stream_AXIS);
        if (stream_PATH != NULL) stream_PATH->free(stream_PATH);
        if (stream_predicate != NULL) stream_predicate->free(stream_predicate);
        if (stream_path != NULL) stream_path->free(stream_path);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end path */

/** 
 * $ANTLR start predicate
 * VerbQueryLanguage.g:78:1: predicate : LBRACKET predicate_expr RBRACKET -> ^( NODE_PREDICATE predicate_expr ) ;
 */
static VerbQueryLanguageParser_predicate_return
predicate(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_predicate_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    LBRACKET26;
    pANTLR3_COMMON_TOKEN    RBRACKET28;
    VerbQueryLanguageParser_predicate_expr_return predicate_expr27;
    #undef	RETURN_TYPE_predicate_expr27
    #define	RETURN_TYPE_predicate_expr27 VerbQueryLanguageParser_predicate_expr_return

    pANTLR3_BASE_TREE LBRACKET26_tree;
    pANTLR3_BASE_TREE RBRACKET28_tree;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_LBRACKET;
    pANTLR3_REWRITE_RULE_TOKEN_STREAM stream_RBRACKET;
    pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_predicate_expr;
    /* Initialize rule variables
     */


    root_0 = NULL;

    LBRACKET26       = NULL;
    RBRACKET28       = NULL;
    predicate_expr27.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    LBRACKET26_tree   = NULL;
    RBRACKET28_tree   = NULL;

    stream_LBRACKET   = NULL;
    #define CREATE_stream_LBRACKET  if (stream_LBRACKET == NULL) {stream_LBRACKET = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token LBRACKET"); } 
    stream_RBRACKET   = NULL;
    #define CREATE_stream_RBRACKET  if (stream_RBRACKET == NULL) {stream_RBRACKET = antlr3RewriteRuleTOKENStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"token RBRACKET"); } 
    stream_predicate_expr   = NULL;
    #define CREATE_stream_predicate_expr  if (stream_predicate_expr == NULL) {stream_predicate_expr = antlr3RewriteRuleSubtreeStreamNewAE(ADAPTOR, RECOGNIZER, (pANTLR3_UINT8)"rule predicate_expr"); }

    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:79:2: ( LBRACKET predicate_expr RBRACKET -> ^( NODE_PREDICATE predicate_expr ) )
        // VerbQueryLanguage.g:79:4: LBRACKET predicate_expr RBRACKET
        {
            LBRACKET26 = (pANTLR3_COMMON_TOKEN) MATCHT(LBRACKET, &FOLLOW_LBRACKET_in_predicate521); 
            if  (HASEXCEPTION())
            {
                goto rulepredicateEx;
            }
             
            CREATE_stream_LBRACKET; stream_LBRACKET->add(stream_LBRACKET, LBRACKET26, NULL);

            FOLLOWPUSH(FOLLOW_predicate_expr_in_predicate523);
            predicate_expr27=predicate_expr(ctx);

            FOLLOWPOP();
            if  (HASEXCEPTION())
            {
                goto rulepredicateEx;
            }

            CREATE_stream_predicate_expr; stream_predicate_expr->add(stream_predicate_expr, predicate_expr27.tree, NULL);
            RBRACKET28 = (pANTLR3_COMMON_TOKEN) MATCHT(RBRACKET, &FOLLOW_RBRACKET_in_predicate525); 
            if  (HASEXCEPTION())
            {
                goto rulepredicateEx;
            }
             
            CREATE_stream_RBRACKET; stream_RBRACKET->add(stream_RBRACKET, RBRACKET28, NULL);


             
            /* AST REWRITE
             * elements          : predicate_expr
             * token labels      : 
             * rule labels       : retval
             * token list labels : 
             * rule list labels  : 
             */
            {
            	pANTLR3_REWRITE_RULE_SUBTREE_STREAM stream_retval;

            	stream_retval=antlr3RewriteRuleSubtreeStreamNewAEE(ADAPTOR,  RECOGNIZER, (pANTLR3_UINT8)"token retval", retval.tree != NULL ? retval.tree : NULL);

            	root_0			    = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	retval.tree    = root_0;
            	// 79:37: -> ^( NODE_PREDICATE predicate_expr )
            	{
            	    // VerbQueryLanguage.g:79:40: ^( NODE_PREDICATE predicate_expr )
            	    {
            	        pANTLR3_BASE_TREE root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));
            	        root_1 = (pANTLR3_BASE_TREE)(ADAPTOR->becomeRoot(ADAPTOR, (pANTLR3_BASE_TREE)ADAPTOR->createTypeText(ADAPTOR, NODE_PREDICATE, (pANTLR3_UINT8)"NODE_PREDICATE"), root_1));

            	        ADAPTOR->addChild(ADAPTOR, root_1, stream_predicate_expr == NULL ? NULL : stream_predicate_expr->nextTree(stream_predicate_expr));

            	        ADAPTOR->addChild(ADAPTOR, root_0, root_1);
            	    }

            	}

            	retval.tree = root_0; // set result root
            	if (stream_retval != NULL) stream_retval->free(stream_retval);


            }
        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepredicateEx; /* Prevent compiler warnings */
    rulepredicateEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);
        if (stream_LBRACKET != NULL) stream_LBRACKET->free(stream_LBRACKET);
        if (stream_RBRACKET != NULL) stream_RBRACKET->free(stream_RBRACKET);
        if (stream_predicate_expr != NULL) stream_predicate_expr->free(stream_predicate_expr);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end predicate */

/** 
 * $ANTLR start predicate_expr
 * VerbQueryLanguage.g:82:1: predicate_expr : ( INT | predicate_value_expr predicate_oper predicate_value_expr );
 */
static VerbQueryLanguageParser_predicate_expr_return
predicate_expr(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_predicate_expr_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    INT29;
    VerbQueryLanguageParser_predicate_value_expr_return predicate_value_expr30;
    #undef	RETURN_TYPE_predicate_value_expr30
    #define	RETURN_TYPE_predicate_value_expr30 VerbQueryLanguageParser_predicate_value_expr_return

    VerbQueryLanguageParser_predicate_oper_return predicate_oper31;
    #undef	RETURN_TYPE_predicate_oper31
    #define	RETURN_TYPE_predicate_oper31 VerbQueryLanguageParser_predicate_oper_return

    VerbQueryLanguageParser_predicate_value_expr_return predicate_value_expr32;
    #undef	RETURN_TYPE_predicate_value_expr32
    #define	RETURN_TYPE_predicate_value_expr32 VerbQueryLanguageParser_predicate_value_expr_return

    pANTLR3_BASE_TREE INT29_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    INT29       = NULL;
    predicate_value_expr30.tree = NULL;

    predicate_oper31.tree = NULL;

    predicate_value_expr32.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;

    INT29_tree   = NULL;


    retval.tree  = NULL;
    {
        {
            //  VerbQueryLanguage.g:83:3: ( INT | predicate_value_expr predicate_oper predicate_value_expr )
            
            ANTLR3_UINT32 alt11;

            alt11=2;

            switch ( LA(1) ) 
            {
            case INT:
            	{
            		switch ( LA(2) ) 
            		{
            		case EQUALITY:
            		case EQUALITY_ALT:
            		case INEQUALITY:
            		case INEQUALITY_ALT:
            		case LESS:
            		case LTE:
            		case GREATER:
            		case GTE:
            		case AND:
            		case OR:
            		case AND_ALT:
            		case OR_ALT:
            			{
            				alt11=2;
            			}
            		    break;
            		case RBRACKET:
            			{
            				alt11=1;
            			}
            		    break;

            		default:
            		    CONSTRUCTEX();
            		    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            		    EXCEPTION->message      = (void *)"";
            		    EXCEPTION->decisionNum  = 11;
            		    EXCEPTION->state        = 1;


            		    goto rulepredicate_exprEx;
            		}

            	}
                break;
            case AT:
            case PATH:
            case VARIABLE:
            case STRING:
            case FLOAT:
            case FUNCTION:
            case AXIS:
            	{
            		alt11=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 11;
                EXCEPTION->state        = 0;


                goto rulepredicate_exprEx;
            }

            switch (alt11) 
            {
        	case 1:
        	    // VerbQueryLanguage.g:83:5: INT
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        INT29 = (pANTLR3_COMMON_TOKEN) MATCHT(INT, &FOLLOW_INT_in_predicate_expr546); 
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepredicate_exprEx;
        	        }

        	        INT29_tree = (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, INT29));
        	        ADAPTOR->addChild(ADAPTOR, root_0, INT29_tree);


        	    }
        	    break;
        	case 2:
        	    // VerbQueryLanguage.g:84:4: predicate_value_expr predicate_oper predicate_value_expr
        	    {
        	        root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

        	        FOLLOWPUSH(FOLLOW_predicate_value_expr_in_predicate_expr551);
        	        predicate_value_expr30=predicate_value_expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepredicate_exprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, predicate_value_expr30.tree);
        	        FOLLOWPUSH(FOLLOW_predicate_oper_in_predicate_expr553);
        	        predicate_oper31=predicate_oper(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepredicate_exprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, predicate_oper31.tree);
        	        FOLLOWPUSH(FOLLOW_predicate_value_expr_in_predicate_expr555);
        	        predicate_value_expr32=predicate_value_expr(ctx);

        	        FOLLOWPOP();
        	        if  (HASEXCEPTION())
        	        {
        	            goto rulepredicate_exprEx;
        	        }

        	        ADAPTOR->addChild(ADAPTOR, root_0, predicate_value_expr32.tree);

        	    }
        	    break;

            }
        }
    }
    

    // This is where rules clean up and exit
    //
    goto rulepredicate_exprEx; /* Prevent compiler warnings */
    rulepredicate_exprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end predicate_expr */

/** 
 * $ANTLR start predicate_value_expr
 * VerbQueryLanguage.g:87:1: predicate_value_expr : ( value | function | path ) ;
 */
static VerbQueryLanguageParser_predicate_value_expr_return
predicate_value_expr(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_predicate_value_expr_return retval;

    pANTLR3_BASE_TREE root_0;

    VerbQueryLanguageParser_value_return value33;
    #undef	RETURN_TYPE_value33
    #define	RETURN_TYPE_value33 VerbQueryLanguageParser_value_return

    VerbQueryLanguageParser_function_return function34;
    #undef	RETURN_TYPE_function34
    #define	RETURN_TYPE_function34 VerbQueryLanguageParser_function_return

    VerbQueryLanguageParser_path_return path35;
    #undef	RETURN_TYPE_path35
    #define	RETURN_TYPE_path35 VerbQueryLanguageParser_path_return


    /* Initialize rule variables
     */


    root_0 = NULL;

    value33.tree = NULL;

    function34.tree = NULL;

    path35.tree = NULL;

    retval.start = LT(1); retval.stop = retval.start;



    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:88:2: ( ( value | function | path ) )
        // VerbQueryLanguage.g:88:4: ( value | function | path )
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));


            // VerbQueryLanguage.g:88:4: ( value | function | path )
            {
                int alt12=3;
                switch ( LA(1) ) 
                {
                case VARIABLE:
                case STRING:
                case INT:
                case FLOAT:
                	{
                		alt12=1;
                	}
                    break;
                case FUNCTION:
                	{
                		alt12=2;
                	}
                    break;
                case AT:
                case PATH:
                case AXIS:
                	{
                		alt12=3;
                	}
                    break;

                default:
                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 12;
                    EXCEPTION->state        = 0;


                    goto rulepredicate_value_exprEx;
                }

                switch (alt12) 
                {
            	case 1:
            	    // VerbQueryLanguage.g:88:5: value
            	    {
            	        FOLLOWPUSH(FOLLOW_value_in_predicate_value_expr568);
            	        value33=value(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulepredicate_value_exprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, value33.tree);

            	    }
            	    break;
            	case 2:
            	    // VerbQueryLanguage.g:88:13: function
            	    {
            	        FOLLOWPUSH(FOLLOW_function_in_predicate_value_expr572);
            	        function34=function(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulepredicate_value_exprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, function34.tree);

            	    }
            	    break;
            	case 3:
            	    // VerbQueryLanguage.g:88:24: path
            	    {
            	        FOLLOWPUSH(FOLLOW_path_in_predicate_value_expr576);
            	        path35=path(ctx);

            	        FOLLOWPOP();
            	        if  (HASEXCEPTION())
            	        {
            	            goto rulepredicate_value_exprEx;
            	        }

            	        ADAPTOR->addChild(ADAPTOR, root_0, path35.tree);

            	    }
            	    break;

                }
            }

        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepredicate_value_exprEx; /* Prevent compiler warnings */
    rulepredicate_value_exprEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end predicate_value_expr */

/** 
 * $ANTLR start predicate_oper
 * VerbQueryLanguage.g:91:1: predicate_oper : ( EQUALITY | EQUALITY_ALT | INEQUALITY | INEQUALITY_ALT | LESS | LTE | GREATER | GTE | AND | AND_ALT | OR | OR_ALT );
 */
static VerbQueryLanguageParser_predicate_oper_return
predicate_oper(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_predicate_oper_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set36;

    pANTLR3_BASE_TREE set36_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    set36       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    set36_tree   = NULL;


    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:92:2: ( EQUALITY | EQUALITY_ALT | INEQUALITY | INEQUALITY_ALT | LESS | LTE | GREATER | GTE | AND | AND_ALT | OR | OR_ALT )
        // VerbQueryLanguage.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            set36=(pANTLR3_COMMON_TOKEN)LT(1);
            if ( ((LA(1) >= EQUALITY) && (LA(1) <= OR)) || ((LA(1) >= AND_ALT) && (LA(1) <= OR_ALT)) )
            {
                CONSUME();
                ADAPTOR->addChild(ADAPTOR, root_0, (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set36)));
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else 
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = &FOLLOW_set_in_predicate_oper0;
                RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_predicate_oper0);    goto rulepredicate_operEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto rulepredicate_operEx; /* Prevent compiler warnings */
    rulepredicate_operEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end predicate_oper */

/** 
 * $ANTLR start oper
 * VerbQueryLanguage.g:95:1: oper : ( EQUALITY | EQUALITY_ALT | INEQUALITY | INEQUALITY_ALT | LESS | LTE | GREATER | GTE | AND | AND_ALT | OR | OR_ALT | XOR | XOR_ALT | ADD | SUB | MULT | SLASH | MOD );
 */
static VerbQueryLanguageParser_oper_return
oper(pVerbQueryLanguageParser ctx)
{   
    VerbQueryLanguageParser_oper_return retval;

    pANTLR3_BASE_TREE root_0;

    pANTLR3_COMMON_TOKEN    set37;

    pANTLR3_BASE_TREE set37_tree;

    /* Initialize rule variables
     */


    root_0 = NULL;

    set37       = NULL;
    retval.start = LT(1); retval.stop = retval.start;

    set37_tree   = NULL;


    retval.tree  = NULL;
    {
        // VerbQueryLanguage.g:96:2: ( EQUALITY | EQUALITY_ALT | INEQUALITY | INEQUALITY_ALT | LESS | LTE | GREATER | GTE | AND | AND_ALT | OR | OR_ALT | XOR | XOR_ALT | ADD | SUB | MULT | SLASH | MOD )
        // VerbQueryLanguage.g:
        {
            root_0 = (pANTLR3_BASE_TREE)(ADAPTOR->nilNode(ADAPTOR));

            set37=(pANTLR3_COMMON_TOKEN)LT(1);
            if ( LA(1) == SLASH || ((LA(1) >= EQUALITY) && (LA(1) <= XOR)) || ((LA(1) >= ADD) && (LA(1) <= MOD)) || ((LA(1) >= AND_ALT) && (LA(1) <= XOR_ALT)) )
            {
                CONSUME();
                ADAPTOR->addChild(ADAPTOR, root_0, (pANTLR3_BASE_TREE)(ADAPTOR->create(ADAPTOR, set37)));
                PERRORRECOVERY=ANTLR3_FALSE;
            }
            else 
            {
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;
                EXCEPTION->expectingSet = &FOLLOW_set_in_oper0;
                RECOVERFROMMISMATCHEDSET(&FOLLOW_set_in_oper0);    goto ruleoperEx;
            }


        }

    }
    

    // This is where rules clean up and exit
    //
    goto ruleoperEx; /* Prevent compiler warnings */
    ruleoperEx: ;
    retval.stop = LT(-1);

    	retval.stop = LT(-1);
    	retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->rulePostProcessing(ADAPTOR, root_0));
    	ADAPTOR->setTokenBoundaries(ADAPTOR, retval.tree, retval.start, retval.stop);

            if (HASEXCEPTION())
            {
                PREPORTERROR();
                PRECOVER();
                retval.tree = (pANTLR3_BASE_TREE)(ADAPTOR->errorNode(ADAPTOR, INPUT, retval.start, LT(-1), EXCEPTION));
            }


    return retval;
}
/* $ANTLR end oper */
/* End of parsing rules
 * ==============================================
 */

/* ==============================================
 * Syntactic predicates
 */
/* End of syntactic predicates
 * ==============================================
 */

 
 



/* End of code
 * =============================================================================
 */
